# Analyse Modern Science Ontology

### Importing Required Libraries

In this cell, we are importing the following libraries:

- `json`: Used for working with JSON data.
- `pandas`: Used for data structurization.
- `deque` from `collections`: Used for creating a double-ended queue.
- `Graph` and `plugin` from `rdflib`: Used for working with RDF data.
- `SPARQLWrapper` from `SPARQLWrapper`: Used for querying RDF data using SPARQL.
- `Serializer` from `rdflib.serializer`: Used for serializing RDF data.

These libraries are necessary for the subsequent cells in this Jupyter Notebook.

In [1]:
import json
import pandas as pd
from collections import deque
from rdflib import Graph, plugin
from SPARQLWrapper import SPARQLWrapper
from rdflib.serializer import Serializer

In [2]:
input_file = "ontology.ttl"

### Parsing the Ontology

In this cell, we are parsing the ontology file using the `Graph().parse()` method from the `rdflib` library. The ontology file is specified by the `input_file` variable, which contains the path to the ontology file.

After parsing the ontology, we print the graph object `g` to display the parsed ontology.

This step is necessary for further analysis and querying of the ontology data.

In [3]:
g = Graph().parse(input_file, format='ttl')
print(g)

[a rdfg:Graph;rdflib:storage [a rdflib:Store;rdfs:label 'Memory']].

### Querying the Ontology

In the following, we are querying the ontology using the `g.query()` method from the `rdflib` library. The query is specified in the SPARQL format and is used to count the number of classes in the ontology.

The query selects all instances of the `owl:Class` and retrieves their labels using the `rdfs:label` property. The result is the count of classes, which is assigned to the variable `?at`.

This step is necessary for further analysis and understanding of the ontology structure.

In [4]:
qres = g.query(
    """PREFIX owl: <http://www.w3.org/2002/07/owl#>

        PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
       SELECT (count(?a) as ?at)
       WHERE {
       ?a a owl:Class .
       ?a rdfs:label ?b .
       }""")

In [5]:
for row in qres:
    print(row.at)

239

In [6]:
modsci_json = g.serialize(format='json-ld', indent=4)

In [7]:
print(modsci_json)

[
    {
        "@id": "https://w3id.org/skgo/modsci#Education",
        "@type": [
            "http://www.w3.org/2002/07/owl#Class"
        ],
        "http://www.w3.org/2000/01/rdf-schema#comment": [
            {
                "@value": "Education is the teaching or learning of knowledge, especially to develop the reasoning, judgement and skill required in adult life and professional occupations."
            }
        ],
        "http://www.w3.org/2000/01/rdf-schema#label": [
            {
                "@value": "Education"
            }
        ],
        "http://www.w3.org/2000/01/rdf-schema#subClassOf": [
            {
                "@id": "https://w3id.org/skgo/modsci#AppliedSciences"
            }
        ]
    },
    {
        "@id": "https://w3id.org/skgo/modsci#Cryobiology",
        "@type": [
            "http://www.w3.org/2002/07/owl#Class"
        ],
        "http://www.w3.org/2000/01/rdf-schema#comment": [
            {
                "@value": "Cryobiology is the study of living organisms, organs, biological tissues or biological cells at low temperatures."
            }
        ],
        "http://www.w3.org/2000/01/rdf-schema#label": [
            {
                "@value": "Cryobiology"
            }
        ],
        "http://www.w3.org/2000/01/rdf-schema#subClassOf": [
            {
                "@id": "https://w3id.org/skgo/modsci#Biology"
            }
        ]
    },
    {
        "@id": "https://w3id.org/skgo/modsci#ProgrammingLanguageTheory",
        "@type": [
            "http://www.w3.org/2002/07/owl#Class"
        ],
        "http://www.w3.org/2000/01/rdf-schema#comment": [
            {
                "@value": "Programming language theory (PLT) is a branch of computer science that deals with the design, implementation, analysis, characterization, and classification of programming languages and their individual features."
            }
        ],
        "http://www.w3.org/2000/01/rdf-schema#label": [
            {
                "@value": "Programming Language Theory"
            }
        ],
        "http://www.w3.org/2000/01/rdf-schema#subClassOf": [
            {
                "@id": "https://w3id.org/skgo/modsci#ProgrammingLanguages"
            }
        ]
    },
    {
        "@id": "https://w3id.org/skgo/modsci#discoveredByNaturalScience",
        "@type": [
            "http://www.w3.org/2002/07/owl#ObjectProperty"
        ],
        "http://www.w3.org/2000/01/rdf-schema#label": [
            {
                "@language": "en",
                "@value": "discovered by natural science"
            }
        ],
        "http://www.w3.org/2000/01/rdf-schema#subPropertyOf": [
            {
                "@id": "https://w3id.org/skgo/modsci#isDiscoveredByScience"
            }
        ]
    },
    {
        "@id": "https://w3id.org/skgo/modsci#OrganicGreenChemistry",
        "@type": [
            "http://www.w3.org/2002/07/owl#Class"
        ],
        "http://www.w3.org/2000/01/rdf-schema#subClassOf": [
            {
                "@id": "https://w3id.org/skgo/modsci#OrganicChemistry"
            }
        ]
    },
    {
        "@id": "https://w3id.org/skgo/modsci#IntegralEquations",
        "@type": [
            "http://www.w3.org/2002/07/owl#Class"
        ],
        "http://www.w3.org/2000/01/rdf-schema#subClassOf": [
            {
                "@id": "https://w3id.org/skgo/modsci#ComputationalMathematics"
            }
        ]
    },
    {
        "@id": "https://w3id.org/skgo/modsci#SoilSciences",
        "@type": [
            "http://www.w3.org/2002/07/owl#Class"
        ],
        "http://www.w3.org/2000/01/rdf-schema#subClassOf": [
            {
                "@id": "https://w3id.org/skgo/modsci#EnvironmentalScience"
            }
        ]
    },
    {
        "@id": "https://w3id.org/skgo/modsci#Forestry",
        "@type": [
            "http://www.w3.org/2002/07/owl#Class"
        ],
        "http://www.w3.org/2000/01/rdf-schema#comment": [
            {
                "@value": "Forestry is the art, science, and practice of studying and managing forests and related natural resources."
            }
        ],
        "http://www.w3.org/2000/01/rdf-schema#label": [
            {
                "@value": "Forestry"
            }
        ],
        "http://www.w3.org/2000/01/rdf-schema#subClassOf": [
            {
                "@id": "https://w3id.org/skgo/modsci#Biology"
            }
        ]
    },
    {
        "@id": "https://w3id.org/skgo/modsci#Ethnology",
        "@type": [
            "http://www.w3.org/2002/07/owl#Class"
        ],
        "http://www.w3.org/2000/01/rdf-schema#comment": [
            {
                "@value": "Ethnology is the science that analyzes human cultures and compares them."
            }
        ],
        "http://www.w3.org/2000/01/rdf-schema#label": [
            {
                "@value": "Ethnology"
            }
        ],
        "http://www.w3.org/2000/01/rdf-schema#subClassOf": [
            {
                "@id": "https://w3id.org/skgo/modsci#SocialSciences"
            }
        ]
    },
    {
        "@id": "https://w3id.org/skgo/modsci#ClassicalPhysics",
        "@type": [
            "http://www.w3.org/2002/07/owl#Class"
        ],
        "http://www.w3.org/2000/01/rdf-schema#subClassOf": [
            {
                "@id": "https://w3id.org/skgo/modsci#Physics"
            }
        ]
    },
    {
        "@id": "https://w3id.org/skgo/modsci#TheoreticalChemistry",
        "@type": [
            "http://www.w3.org/2002/07/owl#Class"
        ],
        "http://www.w3.org/2000/01/rdf-schema#comment": [
            {
                "@value": "Theoretical chemistry is the application of theoretical reasoning to chemistry."
            }
        ],
        "http://www.w3.org/2000/01/rdf-schema#label": [
            {
                "@value": "Theoretical Chemistry"
            }
        ],
        "http://www.w3.org/2000/01/rdf-schema#subClassOf": [
            {
                "@id": "https://w3id.org/skgo/modsci#Chemistry"
            }
        ]
    },
    {
        "@id": "https://w3id.org/skgo/modsci#inventsInstrument",
        "@type": [
            "http://www.w3.org/2002/07/owl#ObjectProperty"
        ],
        "http://www.w3.org/2000/01/rdf-schema#comment": [
            {
                "@language": "en",
                "@value": "A sciientist invents an instrument ."
            }
        ],
        "http://www.w3.org/2000/01/rdf-schema#label": [
            {
                "@language": "en",
                "@value": "invents instrument"
            }
        ]
    },
    {
        "@id": "https://w3id.org/skgo/modsci#TheoryOfComputation",
        "@type": [
            "http://www.w3.org/2002/07/owl#Class"
        ],
        "http://www.w3.org/2000/01/rdf-schema#comment": [
            {
                "@value": "Theory of computation is focused on answering fundamental questions about what can be computed and what amount of resources are required to perform those computations."
            }
        ],
        "http://www.w3.org/2000/01/rdf-schema#label": [
            {
                "@value": "Theory of Computation"
            }
        ],
        "http://www.w3.org/2000/01/rdf-schema#subClassOf": [
            {
                "@id": "https://w3id.org/skgo/modsci#TheoreticalComputerScience"
            }
        ]
    },
    {
        "@id": "https://w3id.org/skgo/modsci#TheoreticalComputerScience",
        "@type": [
            "http://www.w3.org/2002/07/owl#Class"
        ],
        "http://www.w3.org/2000/01/rdf-schema#subClassOf": [
            {
                "@id": "https://w3id.org/skgo/modsci#ComputerScience"
            }
        ]
    },
    {
        "@id": "https://w3id.org/skgo/modsci#EnvironmentalChemistry",
        "@type": [
            "http://www.w3.org/2002/07/owl#Class"
        ],
        "http://www.w3.org/2000/01/rdf-schema#comment": [
            {
                "@value": "Environmental chemistry is the scientific study of the physical, chemical and biochemical properties and processes of polluting substances in the environment."
            }
        ],
        "http://www.w3.org/2000/01/rdf-schema#label": [
            {
                "@value": "Environmental Chemistry"
            }
        ],
        "http://www.w3.org/2000/01/rdf-schema#subClassOf": [
            {
                "@id": "https://w3id.org/skgo/modsci#Chemistry"
            }
        ]
    },
    {
        "@id": "https://w3id.org/skgo/modsci#InstrumentFunctionDesription",
        "@type": [
            "http://www.w3.org/2002/07/owl#DatatypeProperty"
        ],
        "http://www.w3.org/2000/01/rdf-schema#domain": [
            {
                "@id": "https://w3id.org/skgo/modsci#ScientificInstrument"
            }
        ],
        "http://www.w3.org/2000/01/rdf-schema#label": [
            {
                "@language": "en",
                "@value": "Instrument function desription"
            }
        ],
        "http://www.w3.org/2000/01/rdf-schema#range": [
            {
                "@id": "http://www.w3.org/2001/XMLSchema#string"
            }
        ]
    },
    {
        "@id": "https://w3id.org/skgo/modsci#MultimediaProgramming",
        "@type": [
            "http://www.w3.org/2002/07/owl#Class"
        ],
        "http://www.w3.org/2000/01/rdf-schema#subClassOf": [
            {
                "@id": "https://w3id.org/skgo/modsci#ComputerSoftware"
            }
        ]
    },
    {
        "@id": "https://w3id.org/skgo/modsci#Anthropology",
        "@type": [
            "http://www.w3.org/2002/07/owl#Class"
        ],
        "http://www.w3.org/2000/01/rdf-schema#comment": [
            {
                "@value": "Anthropology is the scientific study of humans, human behavior and societies in the past and present."
            }
        ],
        "http://www.w3.org/2000/01/rdf-schema#label": [
            {
                "@value": "Anthropology"
            }
        ],
        "http://www.w3.org/2000/01/rdf-schema#subClassOf": [
            {
                "@id": "https://w3id.org/skgo/modsci#SocialSciences"
            }
        ]
    },
    {
        "@id": "https://w3id.org/skgo/modsci#TypeTheory",
        "@type": [
            "http://www.w3.org/2002/07/owl#Class"
        ],
        "http://www.w3.org/2000/01/rdf-schema#comment": [
            {
                "@value": "In mathematics, logic, and computer science, a type theory is any of a class of formal systems, some of which can serve as alternatives to set theory as a foundation for all mathematics. In type theory, every \"term\" has a \"type\" and operations are restricted to terms of a certain type."
            }
        ],
        "http://www.w3.org/2000/01/rdf-schema#label": [
            {
                "@value": "Type Theory"
            }
        ],
        "http://www.w3.org/2000/01/rdf-schema#subClassOf": [
            {
                "@id": "https://w3id.org/skgo/modsci#ProgrammingLanguages"
            }
        ]
    },
    {
        "@id": "https://w3id.org/skgo/modsci#EvolutionaryBiology",
        "@type": [
            "http://www.w3.org/2002/07/owl#Class"
        ],
        "http://www.w3.org/2000/01/rdf-schema#comment": [
            {
                "@value": "Evolutionary biology is a sub-field of biology concerned with the study of the evolutionary processes that produced the diversity of life on Earth."
            }
        ],
        "http://www.w3.org/2000/01/rdf-schema#label": [
            {
                "@value": "Evolutionary Biology"
            }
        ],
        "http://www.w3.org/2000/01/rdf-schema#subClassOf": [
            {
                "@id": "https://w3id.org/skgo/modsci#Biology"
            }
        ]
    },
    {
        "@id": "https://w3id.org/skgo/modsci#TheoryAndDesignOfMaterials",
        "@type": [
            "http://www.w3.org/2002/07/owl#Class"
        ],
        "http://www.w3.org/2000/01/rdf-schema#subClassOf": [
            {
                "@id": "https://w3id.org/skgo/modsci#MaterialsChemistry"
            }
        ]
    },
    {
        "@id": "https://w3id.org/skgo/modsci#InterorganisationalInformationSystems",
        "@type": [
            "http://www.w3.org/2002/07/owl#Class"
        ],
        "http://www.w3.org/2000/01/rdf-schema#subClassOf": [
            {
                "@id": "https://w3id.org/skgo/modsci#InformationSystems"
            }
        ]
    },
    {
        "@id": "https://w3id.org/skgo/modsci#BioinformaticsSoftware",
        "@type": [
            "http://www.w3.org/2002/07/owl#Class"
        ],
        "http://www.w3.org/2000/01/rdf-schema#subClassOf": [
            {
                "@id": "https://w3id.org/skgo/modsci#ComputerSoftware"
            }
        ]
    },
    {
        "@id": "https://w3id.org/skgo/modsci#AnalyticalChemistry",
        "@type": [
            "http://www.w3.org/2002/07/owl#Class"
        ],
        "http://www.w3.org/2000/01/rdf-schema#comment": [
            {
                "@value": "Analytical chemistry is the analysis of material samples to gain an understanding of their chemical composition and structure."
            }
        ],
        "http://www.w3.org/2000/01/rdf-schema#label": [
            {
                "@value": "Analytical Chemistry"
            }
        ],
        "http://www.w3.org/2000/01/rdf-schema#subClassOf": [
            {
                "@id": "https://w3id.org/skgo/modsci#Chemistry"
            }
        ]
    },
    {
        "@id": "https://w3id.org/skgo/modsci#isApplicationOfBehaviouralSciences",
        "@type": [
            "http://www.w3.org/2002/07/owl#ObjectProperty"
        ],
        "http://www.w3.org/2000/01/rdf-schema#comment": [
            {
                "@language": "en",
                "@value": "An application is an application of behavioural science."
            }
        ],
        "http://www.w3.org/2000/01/rdf-schema#label": [
            {
                "@language": "en",
                "@value": "is application of behavioural science"
            }
        ],
        "http://www.w3.org/2000/01/rdf-schema#subPropertyOf": [
            {
                "@id": "https://w3id.org/skgo/modsci#isApplicationOfScience"
            }
        ]
    },
    {
        "@id": "https://w3id.org/skgo/modsci#TransitionMetalChemistry",
        "@type": [
            "http://www.w3.org/2002/07/owl#Class"
        ],
        "http://www.w3.org/2000/01/rdf-schema#subClassOf": [
            {
                "@id": "https://w3id.org/skgo/modsci#InorganicChemistry"
            }
        ]
    },
    {
        "@id": "https://w3id.org/skgo/modsci#MeteorologicalPhenomena",
        "@type": [
            "http://www.w3.org/2002/07/owl#Class"
        ],
        "http://www.w3.org/2000/01/rdf-schema#label": [
            {
                "@value": "Meteorological Phenomena"
            }
        ],
        "http://www.w3.org/2000/01/rdf-schema#subClassOf": [
            {
                "@id": "https://w3id.org/skgo/modsci#NaturalPhenomenon"
            }
        ]
    },
    {
        "@id": "https://w3id.org/skgo/modsci#BiomedicalEngineering",
        "@type": [
            "http://www.w3.org/2002/07/owl#Class"
        ],
        "http://www.w3.org/2000/01/rdf-schema#comment": [
            {
                "@value": "Biomedical engineering (BME) or medical engineering is the application of engineering principles and design concepts to medicine and biology for healthcare purposes (e.g. diagnostic or therapeutic)."
            }
        ],
        "http://www.w3.org/2000/01/rdf-schema#label": [
            {
                "@value": "Biomedical Engineering"
            }
        ],
        "http://www.w3.org/2000/01/rdf-schema#subClassOf": [
            {
                "@id": "https://w3id.org/skgo/modsci#InterdisciplinaryStudies"
            }
        ]
    },
    {
        "@id": "_:n5cdac68c4c5e43eab9b2b61e66d5d28db26",
        "@type": [
            "http://www.w3.org/2003/11/swrl#Imp"
        ],
        "http://swrl.stanford.edu/ontologies/3.3/swrla.owl#isRuleEnabled": [
            {
                "@value": true
            }
        ],
        "http://www.w3.org/2000/01/rdf-schema#comment": [
            {
                "@value": ""
            }
        ],
        "http://www.w3.org/2000/01/rdf-schema#label": [
            {
                "@value": "S2"
            }
        ],
        "http://www.w3.org/2003/11/swrl#body": [
            {
                "@id": "_:n5cdac68c4c5e43eab9b2b61e66d5d28db27"
            }
        ],
        "http://www.w3.org/2003/11/swrl#head": [
            {
                "@id": "_:n5cdac68c4c5e43eab9b2b61e66d5d28db31"
            }
        ]
    },
    {
        "@id": "_:n5cdac68c4c5e43eab9b2b61e66d5d28db27",
        "@type": [
            "http://www.w3.org/2003/11/swrl#AtomList"
        ],
        "http://www.w3.org/1999/02/22-rdf-syntax-ns#first": [
            {
                "@id": "_:n5cdac68c4c5e43eab9b2b61e66d5d28db28"
            }
        ],
        "http://www.w3.org/1999/02/22-rdf-syntax-ns#rest": [
            {
                "@id": "_:n5cdac68c4c5e43eab9b2b61e66d5d28db29"
            }
        ]
    },
    {
        "@id": "_:n5cdac68c4c5e43eab9b2b61e66d5d28db28",
        "@type": [
            "http://www.w3.org/2003/11/swrl#ClassAtom"
        ],
        "http://www.w3.org/2003/11/swrl#argument1": [
            {
                "@id": "https://w3id.org/skgo/modsci#x"
            }
        ],
        "http://www.w3.org/2003/11/swrl#classPredicate": [
            {
                "@id": "https://w3id.org/skgo/modsci#Scientist"
            }
        ]
    },
    {
        "@id": "_:n5cdac68c4c5e43eab9b2b61e66d5d28db29",
        "@type": [
            "http://www.w3.org/2003/11/swrl#AtomList"
        ],
        "http://www.w3.org/1999/02/22-rdf-syntax-ns#first": [
            {
                "@id": "_:n5cdac68c4c5e43eab9b2b61e66d5d28db30"
            }
        ],
        "http://www.w3.org/1999/02/22-rdf-syntax-ns#rest": [
            {
                "@list": []
            }
        ]
    },
    {
        "@id": "_:n5cdac68c4c5e43eab9b2b61e66d5d28db30",
        "@type": [
            "http://www.w3.org/2003/11/swrl#IndividualPropertyAtom"
        ],
        "http://www.w3.org/2003/11/swrl#argument1": [
            {
                "@id": "https://w3id.org/skgo/modsci#y"
            }
        ],
        "http://www.w3.org/2003/11/swrl#argument2": [
            {
                "@id": "https://w3id.org/skgo/modsci#x"
            }
        ],
        "http://www.w3.org/2003/11/swrl#propertyPredicate": [
            {
                "@id": "https://w3id.org/skgo/modsci#isDiscoveredBy"
            }
        ]
    },
    {
        "@id": "_:n5cdac68c4c5e43eab9b2b61e66d5d28db31",
        "@type": [
            "http://www.w3.org/2003/11/swrl#AtomList"
        ],
        "http://www.w3.org/1999/02/22-rdf-syntax-ns#first": [
            {
                "@id": "_:n5cdac68c4c5e43eab9b2b61e66d5d28db32"
            }
        ],
        "http://www.w3.org/1999/02/22-rdf-syntax-ns#rest": [
            {
                "@list": []
            }
        ]
    },
    {
        "@id": "_:n5cdac68c4c5e43eab9b2b61e66d5d28db32",
        "@type": [
            "http://www.w3.org/2003/11/swrl#IndividualPropertyAtom"
        ],
        "http://www.w3.org/2003/11/swrl#argument1": [
            {
                "@id": "https://w3id.org/skgo/modsci#y"
            }
        ],
        "http://www.w3.org/2003/11/swrl#argument2": [
            {
                "@id": "https://w3id.org/skgo/modsci#x"
            }
        ],
        "http://www.w3.org/2003/11/swrl#propertyPredicate": [
            {
                "@id": "https://w3id.org/skgo/modsci#isDiscoveredByScientist"
            }
        ]
    },
    {

In [8]:
modsci = pd.read_json(modsci_json)
modsci.head(50)

,@id,@type,http://www.w3.org/2000/01/rdf-schema#comment,http://www.w3.org/2000/01/rdf-schema#label,http://www.w3.org/2000/01/rdf-schema#subClassOf,http://www.w3.org/2000/01/rdf-schema#subPropertyOf,http://www.w3.org/2000/01/rdf-schema#domain,http://www.w3.org/2000/01/rdf-schema#range,http://swrl.stanford.edu/ontologies/3.3/swrla.owl#isRuleEnabled,http://www.w3.org/2003/11/swrl#body,...,http://www.w3.org/2002/07/owl#annotatedProperty,http://www.w3.org/2002/07/owl#annotatedSource,http://www.w3.org/2002/07/owl#annotatedTarget,http://www.w3.org/2002/07/owl#allValuesFrom,http://www.w3.org/2002/07/owl#onProperty,http://www.w3.org/2002/07/owl#disjointWith,http://www.w3.org/2004/02/skos/core#definition,http://www.w3.org/2004/02/skos/core#prefLabel,http://purl.org/dc/terms/bibliographicCitation,http://www.w3.org/2000/01/rdf-schema#seeAlso
0,https://w3id.org/skgo/modsci#Education,[http://www.w3.org/2002/07/owl#Class],[{'@value': 'Education is the teaching or lear...,[{'@value': 'Education'}],[{'@id': 'https://w3id.org/skgo/modsci#Applied...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,https://w3id.org/skgo/modsci#Cryobiology,[http://www.w3.org/2002/07/owl#Class],[{'@value': 'Cryobiology is the study of livin...,[{'@value': 'Cryobiology'}],[{'@id': 'https://w3id.org/skgo/modsci#Biology'}],NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,https://w3id.org/skgo/modsci#ProgrammingLangua...,[http://www.w3.org/2002/07/owl#Class],[{'@value': 'Programming language theory (PLT)...,[{'@value': 'Programming Language Theory'}],[{'@id': 'https://w3id.org/skgo/modsci#Program...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,https://w3id.org/skgo/modsci#discoveredByNatur...,[http://www.w3.org/2002/07/owl#ObjectProperty],NaN,"[{'@language': 'en', '@value': 'discovered by ...",NaN,[{'@id': 'https://w3id.org/skgo/modsci#isDisco...,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,https://w3id.org/skgo/modsci#OrganicGreenChemi...,[http://www.w3.org/2002/07/owl#Class],NaN,NaN,[{'@id': 'https://w3id.org/skgo/modsci#Organic...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,https://w3id.org/skgo/modsci#IntegralEquations,[http://www.w3.org/2002/07/owl#Class],NaN,NaN,[{'@id': 'https://w3id.org/skgo/modsci#Computa...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,https://w3id.org/skgo/modsci#SoilSciences,[http://www.w3.org/2002/07/owl#Class],NaN,NaN,[{'@id': 'https://w3id.org/skgo/modsci#Environ...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,https://w3id.org/skgo/modsci#Forestry,[http://www.w3.org/2002/07/owl#Class],"[{'@value': 'Forestry is the art, science, and...",[{'@value': 'Forestry'}],[{'@id': 'https://w3id.org/skgo/modsci#Biology'}],NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,https://w3id.org/skgo/modsci#Ethnology,[http://www.w3.org/2002/07/owl#Class],[{'@value': 'Ethnology is the science that ana...,[{'@value': 'Ethnology'}],[{'@id': 'https://w3id.org/skgo/modsci#SocialS...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,https://w3id.org/skgo/modsci#ClassicalPhysics,[http://www.w3.org/2002/07/owl#Class],NaN,NaN,[{'@id': 'https://w3id.org/skgo/modsci#Physics'}],NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,https://w3id.org/skgo/modsci#TheoreticalChemistry,[http://www.w3.org/2002/07/owl#Class],[{'@value': 'Theoretical chemistry is the appl...,[{'@value': 'Theoretical Chemistry'}],[{'@id': 'https://w3id.org/skgo/modsci#Chemist...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,https://w3id.org/skgo/modsci#inventsInstrument,[http://www.w3.org/2002/07/owl#ObjectProperty],"[{'@language': 'en', '@value': 'A sciientist i...","[{'@language': 'en', '@value': 'invents instru...",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,https://w3id.org/skgo/modsci#TheoryOfComputation,[http://www.w3.org/2002/07/owl#Class],[{'@value': 'Theory of computation is focused ...,[{'@value': 'Theory of Computation'}],[{'@id': 'https://w3id.org/skgo/modsci#Theoret...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,https://w3id.org/skgo/modsci#TheoreticalComput...,[http://www.w3.org/2002/07/owl#Class],NaN,NaN,[{'@id': 'https://w3id.org/skgo/modsci#Compute...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,https://w3id.org/skgo/modsci#EnvironmentalChem...,[http://www.w3.org/2002/07/owl#Class],[{'@value': 'Environmental chemistry is the sc...,[{'@value': 'Environmental Chemistry'}],[{'@id': 'https://w3id.org/skgo/modsci#Chemist...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,https://w3id.org/skgo/modsci#InstrumentFunctio...,[http://www.w3.org/2002/07/owl#DatatypeProperty],NaN,"[{'@language': 'en', '@value': 'Instrument fun...",NaN,NaN,[{'@id': 'https://w3id.org/skgo/modsci#Scienti...,[{'@id': 'http://www.w3.org/2001/XMLSchema#str...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,https://w3id.org/skgo/modsci#MultimediaProgram...,[http://www.w3.org/2002/07/owl#Class],NaN,NaN,[{'@id': 'https://w3id.org/skgo/modsci#Compute...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,https://w3id.org/skgo/modsci#Anthropology,[http://www.w3.org/2002/07/owl#Class],[{'@value': 'Anthropology is the scientific st...,[{'@value': 'Anthropology'}],[{'@id': 'https://w3id.org/skgo/modsci#SocialS...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,https://w3id.org/skgo/modsci#TypeTheory,[http://www.w3.org/2002/07/owl#Class],"[{'@value': 'In mathematics, logic, and comput...",[{'@value': 'Type Theory'}],[{'@id': 'https://w3id.org/skgo/modsci#Program...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,https://w3id.org/skgo/modsci#EvolutionaryBiology,[http://www.w3.org/2002/07/owl#Class],[{'@value': 'Evolutionary biology is a sub-fie...,[{'@value': 'Evolutionary Biology'}],[{'@id': 'https://w3id.org/skgo/modsci#Biology'}],NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,https://w3id.org/skgo/modsci#TheoryAndDesignOf...,[http://www.w3.org/2002/07/owl#Class],NaN,NaN,[{'@id': 'https://w3id.org/skgo/modsci#Materia...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,https://w3id.org/skgo/modsci#Interorganisation...,[http://www.w3.org/2002/07/owl#Class],NaN,NaN,[{'@id': 'https://w3id.org/skgo/modsci#Informa...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,https://w3id.org/skgo/modsci#BioinformaticsSof...,[http://www.w3.org/2002/07/owl#Class],NaN,NaN,[{'@id': 'https://w3id.org/skgo/modsci#Compute...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,https://w3id.org/skgo/modsci#AnalyticalChemistry,[http://www.w3.org/2002/07/owl#Class],[{'@value': 'Analytical chemistry is the analy...,[{'@value': 'Analytical Chemistry'}],[{'@id': 'https://w3id.org/skgo/modsci#Chemist...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,https://w3id.org/skgo/modsci#isApplicationOfBe...,[http://www.w3.org/2002/07/owl#ObjectProperty],"[{'@language': 'en', '@value': 'An application...","[{'@language': 'en', '@value': 'is application...",NaN,[{'@id': 'https://w3id.org/skgo/modsci#isAppli...,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,https://w3id.org/skgo/modsci#TransitionMetalCh...,[http://www.w3.org/2002/07/owl#Class],NaN,NaN,[{'@id': 'https://w3id.org/skgo/modsci#Inorgan...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,https://w3id.org/skgo/modsci#MeteorologicalPhe...,[http://www.w3.org/2002/07/owl#Class],NaN,[{'@value': 'Meteorological Phenomena'}],[{'@id': 'https://w3id.org/skgo/modsci#Natural...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,https://w3id.org/skgo/modsci#BiomedicalEnginee...,[http://www.w3.org/2002/07/owl#Class],[{'@value': 'Biomedical engineering (BME) or m...,[{'@value': 'Biomedical Engineering'}],[{'@id': 'https://w3id.org/skgo/modsci#Interdi...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,_:n5cdac68c4c5e43eab9b2b61e66d5d28db26,[http://www.w3.org/2003/11/swrl#Imp],[{'@value': ''}],[{'@value': 'S2'}],NaN,NaN,NaN,NaN,[{'@value': True}],[{'@id': '_:n5cdac68c4c5e43eab9b2b61e66d5d28db...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,_:n5cdac68c4c5e43eab9b2b61e66d5d28db27,[http://www.w3.org/2003/11/swrl#AtomList],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,_:n5cdac68c4c5e43eab9b2b61e66d5d28db28,[http://www.w3.org/2003/11/swrl#ClassAtom],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,_:n5cdac68c4c5e43eab9b2b61e66d5d28db29,[http://www.w3.org/2003/11/swrl#AtomList],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,_:n5cdac68c4c5e43eab9b2b61e66d5d28db30,[http://www.w3.org/2003/11/swrl#IndividualProp...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,_:n5cdac68c4c5e43eab9b2b61e66d5d28db31,[http://www.w3.org/2003/11/swrl#AtomList],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,_:n5cdac68c4c5e43eab9b2b61e66d5d28db32,[http://www.w3.org/2003/11/swrl#IndividualProp...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,https://w3id.org/skgo/modsci#BehaviouralSciences,[http://www.w3.org/2002/07/owl#Class],[{'@value': 'Behavioural sciences explore the ...,[{'@value': 'Behavioural Sciences'}],[{'@id': 'https://w3id.org/skgo/modsci#ModernS...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,https://w3id.org/skgo/modsci#NumberTheory,[http://www.w3.org/2002/07/owl#Class],NaN,NaN,[{'@id': 'https://w3id.org/skgo/modsci#PureMat...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,https://w3id.org/skgo/modsci#Biogeography,[http://www.w3.org/2002/07/owl#Class],[{'@value': 'Biogeography is the study of the ...,[{'@value': 'Biogeography'}],[{'@id': 'https://w3id.org/skgo/modsci#Biology'}],NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,https://w3id.org/skgo/modsci#isApplicationOfSc...,[http://www.w3.org/2002/07/owl#ObjectProperty],"[{'@language': 'en', '@value': 'An application...","[{'@language': 'en', '@value': 'is application...",NaN,NaN,[{'@id': 'https://w3id.org/skgo/modsci#Applica...,[{'@id': 'https://w3id.org/skgo/modsci#ModernS...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,https://w3id.org/skgo/modsci#BiologicalOceanog...,[http://www.w3.org/2002/07/owl#Class],NaN,NaN,[{'@id': 'https://w3id.org/skgo/modsci#Oceanog...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,https://w3id.org/skgo/modsci#Healthcare,[http://www.w3.org/2002/07/owl#Class],[{'@value': 'Healthcare is the maintenance or ...,[{'@value': 'Healthcare'}],[{'@id': 'https://w3id.org/skgo/modsci#HealthS...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,https://w3id.org/skgo/modsci#StructuredStorage,[http://www.w3.org/2002/07/owl#Class],[{'@value': 'Structured storage is computer st...,[{'@value': 'Structured Storage'}],[{'@id': 'https://w3id.org/skgo/modsci#Databas...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,https://w3id.org/skgo/modsci#AtmosphericPhenomena,[http://www.w3.org/2002/07/owl#Class],NaN,[{'@value': 'Atmospheric Optical Phenomena'}],[{'@id': 'https://w3id.org/skgo/modsci#Natural...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,https://w3id.org/skgo/modsci#DevelopmentalBiology,[http://www.w3.org/2002/07/owl#Class],[{'@value': 'Developmental biology is the stud...,[{'@value': 'Developmental Biology'}],[{'@id': 'https://w3id.org/skgo/modsci#Biology'}],NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,https://w3id.org/skgo/modsci#,[http://www.w3.org/2002/07/owl#Ontology],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,https://w3id.org/skgo/modsci#DataMining,[http://www.w3.org/2002/07/owl#Class],[{'@value': 'Data mining is the process of dis...,[{'@value': 'Data Mining'}],[{'@id': 'https://w3id.org/skgo/modsci#Databas...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,https://w3id.org/skgo/modsci#NonlinearOptics,[http://www.w3.org/2002/07/owl#Class],NaN,NaN,[{'@id': 'https://w3id.org/skgo/modsci#Optical...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,https://w3id.org/skgo/modsci#f-BlockChemistry,[http://www.w3.org/2002/07/owl#Class],NaN,NaN,[{'@id': 'https://w3id.org/skgo/modsci#Inorgan...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,https://w3id.org/skgo/modsci#Paleoclimatology,[http://www.w3.org/2002/07/owl#Class],[{'@value': 'Paleoclimatology is the study of ...,[{'@value': 'Paleoclimatology'}],[{'@id': 'https://w3id.org/skgo/modsci#EarthSc...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,https://w3id.org/skgo/modsci#OreDepositPetrology,[http://www.w3.org/2002/07/owl#Class],NaN,NaN,[{'@id': 'https://w3id.org/skgo/modsci#Geology'}],NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
modsci1 = modsci[["@id","http://www.w3.org/2000/01/rdf-schema#subClassOf"]][modsci['@id'].str.contains("w3id") 
                                                                            &
                                                                            modsci['http://www.w3.org/2000/01/rdf-schema#subClassOf'].notnull()]

In [10]:
modsci1.head(20)

,@id,http://www.w3.org/2000/01/rdf-schema#subClassOf
0,https://w3id.org/skgo/modsci#Education,[{'@id': 'https://w3id.org/skgo/modsci#Applied...
1,https://w3id.org/skgo/modsci#Cryobiology,[{'@id': 'https://w3id.org/skgo/modsci#Biology'}]
2,https://w3id.org/skgo/modsci#ProgrammingLangua...,[{'@id': 'https://w3id.org/skgo/modsci#Program...
4,https://w3id.org/skgo/modsci#OrganicGreenChemi...,[{'@id': 'https://w3id.org/skgo/modsci#Organic...
5,https://w3id.org/skgo/modsci#IntegralEquations,[{'@id': 'https://w3id.org/skgo/modsci#Computa...
6,https://w3id.org/skgo/modsci#SoilSciences,[{'@id': 'https://w3id.org/skgo/modsci#Environ...
7,https://w3id.org/skgo/modsci#Forestry,[{'@id': 'https://w3id.org/skgo/modsci#Biology'}]
8,https://w3id.org/skgo/modsci#Ethnology,[{'@id': 'https://w3id.org/skgo/modsci#SocialS...
9,https://w3id.org/skgo/modsci#ClassicalPhysics,[{'@id': 'https://w3id.org/skgo/modsci#Physics'}]
10,https://w3id.org/skgo/modsci#TheoreticalChemistry,[{'@id': 'https://w3id.org/skgo/modsci#Chemist...
12,https://w3id.org/skgo/modsci#TheoryOfComputation,[{'@id': 'https://w3id.org/skgo/modsci#Theoret...
13,https://w3id.org/skgo/modsci#TheoreticalComput...,[{'@id': 'https://w3id.org/skgo/modsci#Compute...
14,https://w3id.org/skgo/modsci#EnvironmentalChem...,[{'@id': 'https://w3id.org/skgo/modsci#Chemist...
16,https://w3id.org/skgo/modsci#MultimediaProgram...,[{'@id': 'https://w3id.org/skgo/modsci#Compute...
17,https://w3id.org/skgo/modsci#Anthropology,[{'@id': 'https://w3id.org/skgo/modsci#SocialS...
18,https://w3id.org/skgo/modsci#TypeTheory,[{'@id': 'https://w3id.org/skgo/modsci#Program...
19,https://w3id.org/skgo/modsci#EvolutionaryBiology,[{'@id': 'https://w3id.org/skgo/modsci#Biology'}]
20,https://w3id.org/skgo/modsci#TheoryAndDesignOf...,[{'@id': 'https://w3id.org/skgo/modsci#Materia...
21,https://w3id.org/skgo/modsci#Interorganisation...,[{'@id': 'https://w3id.org/skgo/modsci#Informa...
22,https://w3id.org/skgo/modsci#BioinformaticsSof...,[{'@id': 'https://w3id.org/skgo/modsci#Compute...

In [11]:
print("{}".format(len(modsci1)))

360

In [12]:
concepts = dict()
for index, row in modsci1.iterrows():
        concepts[row['@id']] = 1

In [13]:
len(concepts)

360

In [14]:
modsci1 = modsci1[["@id","http://www.w3.org/2000/01/rdf-schema#subClassOf"]][~modsci1['@id'].str.contains("https://w3id.org/skgo/modsci#ModernScience")]

In [15]:
unhier = dict()
max_length = 0
for index, row in modsci1.iterrows():
    length = 0
    if row['@id'] not in unhier:
        unhier[row['@id']] = list()
    parents = row["http://www.w3.org/2000/01/rdf-schema#subClassOf"]
    for parent in parents:
        unhier[row['@id']].append(parent['@id'])
        length += 1
        if length > max_length:
            max_length = length
            print("{}: {} parents".format(row['@id'], max_length))

https://w3id.org/skgo/modsci#Education: 1 parents
https://w3id.org/skgo/modsci#AppliedPhysics: 2 parents
https://w3id.org/skgo/modsci#NaturalLanguageProcessing: 3 parents

In [16]:
print(max_length)

3

In [17]:
print(json.dumps(unhier, indent=4))

{
    "https://w3id.org/skgo/modsci#Education": [
        "https://w3id.org/skgo/modsci#AppliedSciences"
    ],
    "https://w3id.org/skgo/modsci#Cryobiology": [
        "https://w3id.org/skgo/modsci#Biology"
    ],
    "https://w3id.org/skgo/modsci#ProgrammingLanguageTheory": [
        "https://w3id.org/skgo/modsci#ProgrammingLanguages"
    ],
    "https://w3id.org/skgo/modsci#OrganicGreenChemistry": [
        "https://w3id.org/skgo/modsci#OrganicChemistry"
    ],
    "https://w3id.org/skgo/modsci#IntegralEquations": [
        "https://w3id.org/skgo/modsci#ComputationalMathematics"
    ],
    "https://w3id.org/skgo/modsci#SoilSciences": [
        "https://w3id.org/skgo/modsci#EnvironmentalScience"
    ],
    "https://w3id.org/skgo/modsci#Forestry": [
        "https://w3id.org/skgo/modsci#Biology"
    ],
    "https://w3id.org/skgo/modsci#Ethnology": [
        "https://w3id.org/skgo/modsci#SocialSciences"
    ],
    "https://w3id.org/skgo/modsci#ClassicalPhysics": [
        "https://w3id.org/skgo/modsci#Physics"
    ],
    "https://w3id.org/skgo/modsci#TheoreticalChemistry": [
        "https://w3id.org/skgo/modsci#Chemistry"
    ],
    "https://w3id.org/skgo/modsci#TheoryOfComputation": [
        "https://w3id.org/skgo/modsci#TheoreticalComputerScience"
    ],
    "https://w3id.org/skgo/modsci#TheoreticalComputerScience": [
        "https://w3id.org/skgo/modsci#ComputerScience"
    ],
    "https://w3id.org/skgo/modsci#EnvironmentalChemistry": [
        "https://w3id.org/skgo/modsci#Chemistry"
    ],
    "https://w3id.org/skgo/modsci#MultimediaProgramming": [
        "https://w3id.org/skgo/modsci#ComputerSoftware"
    ],
    "https://w3id.org/skgo/modsci#Anthropology": [
        "https://w3id.org/skgo/modsci#SocialSciences"
    ],
    "https://w3id.org/skgo/modsci#TypeTheory": [
        "https://w3id.org/skgo/modsci#ProgrammingLanguages"
    ],
    "https://w3id.org/skgo/modsci#EvolutionaryBiology": [
        "https://w3id.org/skgo/modsci#Biology"
    ],
    "https://w3id.org/skgo/modsci#TheoryAndDesignOfMaterials": [
        "https://w3id.org/skgo/modsci#MaterialsChemistry"
    ],
    "https://w3id.org/skgo/modsci#InterorganisationalInformationSystems": [
        "https://w3id.org/skgo/modsci#InformationSystems"
    ],
    "https://w3id.org/skgo/modsci#BioinformaticsSoftware": [
        "https://w3id.org/skgo/modsci#ComputerSoftware"
    ],
    "https://w3id.org/skgo/modsci#AnalyticalChemistry": [
        "https://w3id.org/skgo/modsci#Chemistry"
    ],
    "https://w3id.org/skgo/modsci#TransitionMetalChemistry": [
        "https://w3id.org/skgo/modsci#InorganicChemistry"
    ],
    "https://w3id.org/skgo/modsci#MeteorologicalPhenomena": [
        "https://w3id.org/skgo/modsci#NaturalPhenomenon"
    ],
    "https://w3id.org/skgo/modsci#BiomedicalEngineering": [
        "https://w3id.org/skgo/modsci#InterdisciplinaryStudies"
    ],
    "https://w3id.org/skgo/modsci#BehaviouralSciences": [
        "https://w3id.org/skgo/modsci#ModernScience"
    ],
    "https://w3id.org/skgo/modsci#NumberTheory": [
        "https://w3id.org/skgo/modsci#PureMathematics"
    ],
    "https://w3id.org/skgo/modsci#Biogeography": [
        "https://w3id.org/skgo/modsci#Biology"
    ],
    "https://w3id.org/skgo/modsci#BiologicalOceanography": [
        "https://w3id.org/skgo/modsci#Oceanography"
    ],
    "https://w3id.org/skgo/modsci#Healthcare": [
        "https://w3id.org/skgo/modsci#HealthSciences"
    ],
    "https://w3id.org/skgo/modsci#StructuredStorage": [
        "https://w3id.org/skgo/modsci#DatabaseManagement"
    ],
    "https://w3id.org/skgo/modsci#AtmosphericPhenomena": [
        "https://w3id.org/skgo/modsci#NaturalPhenomenon"
    ],
    "https://w3id.org/skgo/modsci#DevelopmentalBiology": [
        "https://w3id.org/skgo/modsci#Biology"
    ],
    "https://w3id.org/skgo/modsci#DataMining": [
        "https://w3id.org/skgo/modsci#DatabaseManagement"
    ],
    "https://w3id.org/skgo/modsci#NonlinearOptics": [
        "https://w3id.org/skgo/modsci#OpticalPhysics"
    ],
    "https://w3id.org/skgo/modsci#f-BlockChemistry": [
        "https://w3id.org/skgo/modsci#InorganicChemistry"
    ],
    "https://w3id.org/skgo/modsci#Paleoclimatology": [
        "https://w3id.org/skgo/modsci#EarthScience"
    ],
    "https://w3id.org/skgo/modsci#OreDepositPetrology": [
        "https://w3id.org/skgo/modsci#Geology"
    ],
    "https://w3id.org/skgo/modsci#Chemistry": [
        "https://w3id.org/skgo/modsci#NaturalScience"
    ],
    "https://w3id.org/skgo/modsci#DifferentialEquations": [
        "https://w3id.org/skgo/modsci#PureMathematics"
    ],
    "https://w3id.org/skgo/modsci#CellBiology": [
        "https://w3id.org/skgo/modsci#Biology"
    ],
    "https://w3id.org/skgo/modsci#ExtragalacticAstronomy": [
        "https://w3id.org/skgo/modsci#Astronomy"
    ],
    "https://w3id.org/skgo/modsci#WebServices": [
        "https://w3id.org/skgo/modsci#InformationSystems"
    ],
    "https://w3id.org/skgo/modsci#PastureProduction": [
        "https://w3id.org/skgo/modsci#Agriculture"
    ],
    "https://w3id.org/skgo/modsci#SocialPhenomenon": [
        "http://sweetontology.net/phen/Phenomenon"
    ],
    "https://w3id.org/skgo/modsci#AppliedPhysics": [
        "https://w3id.org/skgo/modsci#InterdisciplinaryStudies",
        "https://w3id.org/skgo/modsci#Physics"
    ],
    "https://w3id.org/skgo/modsci#Logic": [
        "https://w3id.org/skgo/modsci#InterdisciplinaryStudies"
    ],
    "https://w3id.org/skgo/modsci#Botany": [
        "https://w3id.org/skgo/modsci#Biology"
    ],
    "https://w3id.org/skgo/modsci#Cryptography": [
        "https://w3id.org/skgo/modsci#CommunicationAndSecurity"
    ],
    "https://w3id.org/skgo/modsci#Linguistics": [
        "https://w3id.org/skgo/modsci#SocialSciences"
    ],
    "https://w3id.org/skgo/modsci#Stratigraphy": [
        "https://w3id.org/skgo/modsci#Geology"
    ],
    "https://w3id.org/skgo/modsci#Tectonics": [
        "https://w3id.org/skgo/modsci#Geology"
    ],
    "https://w3id.org/skgo/modsci#Health": [
        "https://w3id.org/skgo/modsci#InterdisciplinaryStudies"
    ],
    "https://w3id.org/skgo/modsci#PetroleumGeology": [
        "https://w3id.org/skgo/modsci#Geology"
    ],
    "https://w3id.org/skgo/modsci#Glaciology": [
        "https://w3id.org/skgo/modsci#EarthScience"
    ],
    "https://w3id.org/skgo/modsci#Sedimentology": [
        "https://w3id.org/skgo/modsci#Geology"
    ],
    "https://w3id.org/skgo/modsci#Stereochemistry": [
        "https://w3id.org/skgo/modsci#Chemistry"
    ],
    "https://w3id.org/skgo/modsci#NaturalLanguageProcessing": [
        "https://w3id.org/skgo/modsci#ArtificialIntelligence",
        "https://w3id.org/skgo/modsci#ComputerSoftware",
        "https://w3id.org/skgo/modsci#Linguistics"
    ],
    "https://w3id.org/skgo/modsci#DiscreteMathematics": [
        "https://w3id.org/skgo/modsci#PureMathematics"
    ],
    "https://w3id.org/skgo/modsci#Physiology": [
        "https://w3id.org/skgo/modsci#Biology"
    ],
    "https://w3id.org/skgo/modsci#BiologicalMathematics": [
        "https://w3id.org/skgo/modsci#AppliedMathematics"
    ],
    "https://w3id.org/skgo/modsci#SoftComputing": [
        "https://w3id.org/skgo/modsci#ArtificialIntelligence"
    ],
    "https://w3id.org/skgo/modsci#Lasers": [
        "https://w3id.org/skgo/modsci#OpticalPhysics"
    ],
    "https://w3id.org/skgo/modsci#BiologicalPhenomena": [
        "https://w3id.org/skgo/modsci#NaturalPhenomenon"
    ],
    "https://w3id.org/skgo/modsci#MetrologicalChemistry": [
        "https://w3id.org/skgo/modsci#AnalyticalChemistry"
    ],
    "https://w3id.org/skgo/modsci#Scientist": [
        "http://xmlns.com/foaf/0.1/Person"
    ],
    "https://w3id.org/skgo/modsci#AtomicPhysics": [
        "https://w3id.org/skgo/modsci#Physics"
    ],
    "https://w3id.org/skgo/modsci#FisheriesSciences": [
        "https://w3id.org/skgo/modsci#Agriculture"
    ],
    "https://w3id.org/skgo/modsci#Zoology": [
        "https://w3id.org/skgo/modsci#Biology"
    ],
    "https://w3id.org/skgo/modsci#Technology": [
        "https://w3id.org/skgo/modsci#FormalScience"
    ],
    "https://w3id.org/skgo/modsci#ScientificOrganization": [
        "http://xmlns.com/foaf/0.1/Organization"
    ],
    "https://w3id.org/skgo/modsci#HumanSciences": [
        "https://w3id.org/skgo/modsci#InterdisciplinaryStudies"
    ],
    "https://w3id.org/skgo/modsci#DecisionSupportSystems": [
        "https://w3id.org/skgo/modsci#InformationSystems"
    ],
    "https://w3id.org/skgo/modsci#AutomatedReasoning": [
        "https://w3id.org/skgo/modsci#ArtificialIntelligence"
    ],
    "https://w3id.org/skgo/modsci#WebSearch": [
        "https://w3id.org/skgo/modsci#InformationRetrieval"
    ],
    "https://w3id.org/skgo/modsci#ScienceStudies": [
        "https://w3id.org/skgo/modsci#InterdisciplinaryStudies"
    ],
    "https://w3id.org/skgo/modsci#MilitaryScience": [
        "https://w3id.org/skgo/modsci#AppliedSciences"
    ],
    "https://w3id.org/skgo/modsci#HealthSciences": [
        "https://w3id.org/skgo/modsci#ModernScience"
    ],
    "https://w3id.org/skgo/modsci#GeologicalSciences": [
        "https://w3id.org/skgo/modsci#EarthScience"
    ],
    "https://w3id.org/skgo/modsci#StellarAstronomy": [
        "https://w3id.org/skgo/modsci#Astronomy"
    ],
    "https://w3id.org/skgo/modsci#Ecology": [
        "https://w3id.org/skgo/modsci#Biology",
        "https://w3id.org/skgo/modsci#EarthScience"
    ],
    "https://w3id.org/skgo/modsci#CommunicationStudies": [
        "https://w3id.org/skgo/modsci#SocialSciences"
    ],
    "https://w3id.org/skgo/modsci#SocialWork": [
        "https://w3id.org/skgo/modsci#HealthSciences"
    ],
    "https://w3id.org/skgo/modsci#StructuralChemistry": [
        "https://w3id.org/skgo/modsci#PhysicalChemistry"
    ],
    "https://w3id.org/skgo/modsci#Radiochemistry": [
        "https://w3id.org/skgo/modsci#Chemistry"
    ],
    "https://w3id.org/skgo/modsci#MarineBiology": [
        "https://w3id.org/skgo/modsci#Biology"
    ],
    "https://w3id.org/skgo/modsci#EvolutionaryComputation": [
        "https://w3id.org/skgo/modsci#SoftComputing"
    ],
    "https://w3id.org/skgo/modsci#Metrology": [
        "https://w3id.org/skgo/modsci#AppliedSciences"
    ],
    "https://w3id.org/skgo/modsci#Archaeology": [
        "https://w3id.org/skgo/modsci#SocialSciences"
    ],
    "https://w3id.org/skgo/modsci#Spectroscopy": [
        "https://w3id.org/skgo/modsci#OpticalPhysics"
    ],
    "https://w3id.org/skgo/modsci#ComputerVision": [
        "https://w3id.org/skgo/modsci#ArtificialIntelligence"
    ],
    "https://w3id.org/skgo/modsci#Pharmacology": [
        "https://w3id.org/skgo/modsci#Biology"
    ],
    "https://w3id.org/skgo/modsci#ComputationalPhysics": [
        "https://w3id.org/skgo/modsci#Physics"
    ],
    "https://w3id.org/skgo/modsci#AcidbaseChemistry": [
        "https://w3id.org/skgo/modsci#Chemistry"
    ],
    "https://w3id.org/skgo/modsci#Radiometrics": [
        "https://w3id.org/skgo/modsci#Geophysics"
    ],
    "https://w3id.org/skgo/modsci#Algebra": [
        "https://w3id.org/skgo/modsci#PureMathematics"
    ],
    "https://w3id.org/skgo/modsci#ClassificationAlgorithms": [
        "https://w3id.org/skgo/modsci#Algorithms"
    ],
    "https://w3id.org/skgo/modsci#Non-equilibriumProcesses": [
        "https://w3id.org/skgo/modsci#PhysicalChemistry"
    ],
    "https://w3id.org/skgo/modsci#Biostatistics": [
        "https://w3id.org/skgo/modsci#Biology"
    ],
    "https://w3id.org/skgo/modsci#Bioethics": [
        "https://w3id.org/skgo/modsci#Biology"
    ],
    "https://w3id.org/skgo/modsci#NaturalScience": [
        "https://w3id.org/skgo/modsci#ModernScience"
    ],
    "https://w3id.org/skgo/modsci#Toxicology": [
        "https://w3id.org/skgo/modsci#Biology"
    ],
    "https://w3id.org/skgo/modsci#History": [
        "https://w3id.org/skgo/modsci#FormalScience"
    ],
    "https://w3id.org/skgo/modsci#SolidStateChemistry": [
        "https://w3id.org/skgo/modsci#InorganicChemistry"
    ],
    "https://w3id.org/skgo/modsci#SupramolecularChemistry": [
        "https://w3id.org/skgo/modsci#MaterialsChemistry"
    ],
    "https://w3id.org/skgo/modsci#FinancialMathematics": [
        "https://w3id.org/skgo/modsci#AppliedMathematics"
    ],
    "https://w3id.org/skgo/modsci#MachineLearning": [
        "https://w3id.org/skgo/modsci#SoftComputing"
    ],
    "https://w3id.org/skgo/modsci#MolecularBiology": [
        "https://w3id.org/skgo/modsci#Biology"
    ],
    "https://w3id.org/skgo/modsci#Nanochemistry": [
        "https://w3id.org/skgo/modsci#MaterialsChemistry"
    ],
    "https://w3id.org/skgo/modsci#SurfaceChemistry": [
        "https://w3id.org/skgo/modsci#PhysicalChemistry"
    ],
    "https://w3id.org/skgo/modsci#InformationSystemsTheory": [
        "https://w3id.org/skgo/modsci#InformationSystems"
    ],
    "https://w3id.org/skgo/modsci#SocialPsychology": [
        "https://w3id.org/skgo/modsci#BehaviouralSciences"
    ],
    "https://w3id.org/skgo/modsci#Ethology": [
        "https://w3id.org/skgo/modsci#BehaviouralSciences"
    ],
    "https://w3id.org/skgo/modsci#Semiotics": [
        "https://w3id.org/skgo/modsci#InterdisciplinaryStudies",
        "https://w3id.org/skgo/modsci#SocialSciences"
    ],
    "https://w3id.org/skgo/modsci#Statistics": [
        "https://w3id.org/skgo/modsci#FormalScience"
    ],
    "https://w3id.org/skgo/modsci#RelationalDatabases": [
        "https://w3id.org/skgo/modsci#DatabaseManagement"
    ],
    "https://w3id.org/skgo/modsci#ArtificialIntelligence": [
        "https://w3id.org/skgo/modsci#ComputerScience"
    ],
    "https://w3id.org/skgo/modsci#PartialDifferentialEquations": [
        "https://w3id.org/skgo/modsci#DifferentialEquations"
    ],
    "https://w3id.org/skgo/modsci#InformationVisualization": [
        "https://w3id.org/skgo/modsci#ComputerGraphics"
    ],
    "https://w3id.org/skgo/modsci#VirtualReality": [
        "https://w3id.org/skgo/modsci#ComputerGraphics"
    ],
    "https://w3id.org/skgo/modsci#SolidMechanics": [
        "https://w3id.org/skgo/modsci#Physics"
    ],
    "https://w3id.org/skgo/modsci#MolecularPhysics": [
        "https://w3id.org/skgo/modsci#Physics"
    ],
    "https://w3id.org/skgo/modsci#ElectroanalyticalChemistry": [
        "https://w3id.org/skgo/modsci#AnalyticalChemistry"
    ],
    "https://w3id.org/skgo/modsci#Computer-HumanInteraction": [
        "https://w3id.org/skgo/modsci#InformationSystems"
    ],
    "https://w3id.org/skgo/modsci#Optimisation": [
        "https://w3id.org/skgo/modsci#ComputationalMathematics"
    ],
    "https://w3id.org/skgo/modsci#NaturalPhenomenon": [
        "http://sweetontology.net/phen/Phenomenon"
    ],
    "https://w3id.org/skgo/modsci#Medicine": [
        "https://w3id.org/skgo/modsci#HealthSciences"
    ],
    "https://w3id.org/skgo/modsci#QuantumPhysics": [
        "https://w3id.org/skgo/modsci#Physics"
    ],
    "https://w3id.org/skgo/modsci#OperationsResearch": [
        "https://w3id.org/skgo/modsci#AppliedMathematics"
    ],
    "https://w3id.org/skgo/modsci#Forensics": [
        "https://w3id.org/skgo/modsci#AppliedSciences"
    ],
    "https://w3id.org/skgo/modsci#ChemicalThermodynamics": [
        "https://w3id.org/skgo/modsci#PhysicalChemistry"
    ],
    "https://w3id.org/skgo/modsci#FunctionalAnalysis": [
        "https://w3id.org/skgo/modsci#PureMathematics"
    ],
    "https://w3id.org/skgo/modsci#Geochemistry": [
        "https://w3id.org/skgo/modsci#Chemistry",
        "https://w3id.org/skgo/modsci#Geology"
    ],
    "https://w3id.org/skgo/modsci#Sociobiology": [
        "https://w3id.org/skgo/modsci#BehaviouralSciences",
        "https://w3id.org/skgo/modsci#Biology"
    ],
    "https://w3id.org/skgo/modsci#ComputerSoftware": [
        "https://w3id.org/skgo/modsci#ComputerScience"
    ],
    "https://w3id.org/skgo/modsci#OrdinaryDifferentialEquations": [
        "https://w3id.org/skgo/modsci#DifferentialEquations"
    ],
    "https://w3id.org/skgo/modsci#QuantumMechanics": [
        "https://w3id.org/skgo/modsci#Physics"
    ],
    "https://w3id.org/skgo/modsci#Photochemistry": [
        "https://w3id.org/skgo/modsci#Chemistry"
    ],
    "https://w3id.org/skgo/modsci#Anatomy": [
        "https://w3id.org/skgo/modsci#Biology"
    ],
    "https://w3id.org/skgo/modsci#Pharmacy": [
        "https://w3id.org/skgo/modsci#HealthSciences"
    ],
    "https://w3id.org/skgo/modsci#FreeRadicalChemistry": [
        "https://w3id.org/skgo/modsci#OrganicChemistry"
    ],
    "https://w3id.org/skgo/modsci#Geodynamics": [
        "https://w3id.org/skgo/modsci#Geophysics"
    ],
    "https://w3id.org/skgo/modsci#Sociology": [
        "https://w3id.org/skgo/modsci#SocialSciences"
    ],
    "https://w3id.org/skgo/modsci#ProgrammingLanguage": [
        "https://w3id.org/skgo/modsci#ProgrammingLanguages"
    ],
    "https://w3id.org/skgo/modsci#DiscoveryOfMethods": [
        "https://w3id.org/skgo/modsci#ScientificDiscovery"
    ],
    "https://w3id.org/skgo/modsci#Limnology": [
        "https://w3id.org/skgo/modsci#Biology",
        "https://w3id.org/skgo/modsci#EarthScience"
    ],
    "https://w3id.org/skgo/modsci#GeologicalPhenomena": [
        "https://w3id.org/skgo/modsci#NaturalPhenomenon"
    ],
    "https://w3id.org/skgo/modsci#Networking": [
        "https://w3id.org/skgo/modsci#CommunicationAndSecurity"
    ],
    "https://w3id.org/skgo/modsci#Neuroscience": [
        "https://w3id.org/skgo/modsci#Biology",
        "https://w3id.org/skgo/modsci#InterdisciplinaryStudies"
    ],
    "https://w3id.org/skgo/modsci#WebTechnologies": [
        "https://w3id.org/skgo/modsci#DistributedSystems"
    ],
    "https://w3id.org/skgo/modsci#EvolutionaryPsychology": [
        "https://w3id.org/skgo/modsci#InterdisciplinaryStudies"
    ],
    "https://w3id.org/skgo/modsci#MaterialsChemistry": [
        "https://w3id.org/skgo/modsci#Chemistry"
    ],
    "https://w3id.org/skgo/modsci#ApproximationTheory": [
        "https://w3id.org/skgo/modsci#AppliedMathematics"
    ],
    "https://w3id.org/skgo/modsci#Seismology": [
        "https://w3id.org/skgo/modsci#Geophysics"
    ],
    "https://w3id.org/skgo/modsci#AutomataTheory": [
        "https://w3id.org/skgo/modsci#TheoryOfComputation"
    ],
    "https://w3id.org/skgo/modsci#PhysicalChemistry": [
        "https://w3id.org/skgo/modsci#Chemistry"
    ],
    "https://w3id.org/skgo/modsci#AnalyticalSpectrometry": [
        "https://w3id.org/skgo/modsci#AnalyticalChemistry"
    ],
    "https://w3id.org/skgo/modsci#OceanographicPhenomena": [
        "https://w3id.org/skgo/modsci#NaturalPhenomenon"
    ],
    "https://w3id.org/skgo/modsci#Phylogeny": [
        "https://w3id.org/skgo/modsci#Biology"
    ],
    "https://w3id.org/skgo/modsci#ExtraterrestrialGeology": [
        "https://w3id.org/skgo/modsci#Geology"
    ],
    "https://w3id.org/skgo/modsci#Epidemiology": [
        "https://w3id.org/skgo/modsci#HealthSciences"
    ],
    "https://w3id.org/skgo/modsci#CalculusOfVariations": [
        "https://w3id.org/skgo/modsci#AppliedMathematics"
    ],
    "https://w3id.org/skgo/modsci#Dentistry": [
        "https://w3id.org/skgo/modsci#HealthSciences"
    ],
    "https://w3id.org/skgo/modsci#AppliedMechanics": [
        "https://w3id.org/skgo/modsci#AppliedMathematics"
    ],
    "https://w3id.org/skgo/modsci#Immunology": [
        "https://w3id.org/skgo/modsci#Biology"
    ],
    "https://w3id.org/skgo/modsci#NeuralEngineering": [
        "https://w3id.org/skgo/modsci#InterdisciplinaryStudies"
    ],
    "https://w3id.org/skgo/modsci#ImageProcessing": [
        "https://w3id.org/skgo/modsci#ComputerScience"
    ],
    "https://w3id.org/skgo/modsci#DataFormat": [
        "https://w3id.org/skgo/modsci#ComputerScience"
    ],
    "https://w3id.org/skgo/modsci#QuantumComputing": [
        "https://w3id.org/skgo/modsci#TheoryOfComputation"
    ],
    "https://w3id.org/skgo/modsci#Philosophy": [

In [18]:
def find_max_depth(concepts, unhier):
    for concept, value in concepts.items():
        visited = set()
        queue = deque()
        max_depth = value
        queue.append({"t": concept, "d": value})

        while queue:
            dequeued = queue.popleft()
            concept_name = dequeued["t"]
            depth = dequeued["d"]

            if concept_name in visited:
                continue

            visited.add(concept_name)

            if concept_name in unhier:
                broaders = unhier[concept_name]
                new_depth = depth + 1
                if new_depth > max_depth:
                    max_depth = new_depth
                for broader in broaders:
                    queue.append({"t": broader, "d": depth + 1})

        concepts[concept] = max_depth

In [19]:
find_max_depth(concepts, unhier)
print(concepts)

{'https://w3id.org/skgo/modsci#Education': 3, 'https://w3id.org/skgo/modsci#Cryobiology': 4, 'https://w3id.org/skgo/modsci#ProgrammingLanguageTheory': 6, 'https://w3id.org/skgo/modsci#OrganicGreenChemistry': 5, 'https://w3id.org/skgo/modsci#IntegralEquations': 5, 'https://w3id.org/skgo/modsci#SoilSciences': 5, 'https://w3id.org/skgo/modsci#Forestry': 4, 'https://w3id.org/skgo/modsci#Ethnology': 3, 'https://w3id.org/skgo/modsci#ClassicalPhysics': 4, 'https://w3id.org/skgo/modsci#TheoreticalChemistry': 4, 'https://w3id.org/skgo/modsci#TheoryOfComputation': 5, 'https://w3id.org/skgo/modsci#TheoreticalComputerScience': 4, 'https://w3id.org/skgo/modsci#EnvironmentalChemistry': 4, 'https://w3id.org/skgo/modsci#MultimediaProgramming': 5, 'https://w3id.org/skgo/modsci#Anthropology': 3, 'https://w3id.org/skgo/modsci#TypeTheory': 6, 'https://w3id.org/skgo/modsci#EvolutionaryBiology': 4, 'https://w3id.org/skgo/modsci#TheoryAndDesignOfMaterials': 5, 'https://w3id.org/skgo/modsci#InterorganisationalInformationSystems': 5, 'https://w3id.org/skgo/modsci#BioinformaticsSoftware': 5, 'https://w3id.org/skgo/modsci#AnalyticalChemistry': 4, 'https://w3id.org/skgo/modsci#TransitionMetalChemistry': 5, 'https://w3id.org/skgo/modsci#MeteorologicalPhenomena': 3, 'https://w3id.org/skgo/modsci#BiomedicalEngineering': 3, 'https://w3id.org/skgo/modsci#BehaviouralSciences': 2, 'https://w3id.org/skgo/modsci#NumberTheory': 5, 'https://w3id.org/skgo/modsci#Biogeography': 4, 'https://w3id.org/skgo/modsci#BiologicalOceanography': 5, 'https://w3id.org/skgo/modsci#Healthcare': 3, 'https://w3id.org/skgo/modsci#StructuredStorage': 6, 'https://w3id.org/skgo/modsci#AtmosphericPhenomena': 3, 'https://w3id.org/skgo/modsci#DevelopmentalBiology': 4, 'https://w3id.org/skgo/modsci#DataMining': 6, 'https://w3id.org/skgo/modsci#NonlinearOptics': 5, 'https://w3id.org/skgo/modsci#f-BlockChemistry': 5, 'https://w3id.org/skgo/modsci#Paleoclimatology': 4, 'https://w3id.org/skgo/modsci#OreDepositPetrology': 6, 'https://w3id.org/skgo/modsci#Chemistry': 3, 'https://w3id.org/skgo/modsci#DifferentialEquations': 5, 'https://w3id.org/skgo/modsci#CellBiology': 4, 'https://w3id.org/skgo/modsci#ExtragalacticAstronomy': 4, 'https://w3id.org/skgo/modsci#WebServices': 5, 'https://w3id.org/skgo/modsci#PastureProduction': 4, 'https://w3id.org/skgo/modsci#SocialPhenomenon': 2, 'https://w3id.org/skgo/modsci#AppliedPhysics': 4, 'https://w3id.org/skgo/modsci#Logic': 3, 'https://w3id.org/skgo/modsci#Botany': 4, 'https://w3id.org/skgo/modsci#Cryptography': 6, 'https://w3id.org/skgo/modsci#Linguistics': 3, 'https://w3id.org/skgo/modsci#Stratigraphy': 6, 'https://w3id.org/skgo/modsci#Tectonics': 6, 'https://w3id.org/skgo/modsci#Health': 3, 'https://w3id.org/skgo/modsci#PetroleumGeology': 6, 'https://w3id.org/skgo/modsci#Glaciology': 4, 'https://w3id.org/skgo/modsci#Sedimentology': 6, 'https://w3id.org/skgo/modsci#Stereochemistry': 4, 'https://w3id.org/skgo/modsci#NaturalLanguageProcessing': 5, 'https://w3id.org/skgo/modsci#DiscreteMathematics': 5, 'https://w3id.org/skgo/modsci#Physiology': 4, 'https://w3id.org/skgo/modsci#BiologicalMathematics': 5, 'https://w3id.org/skgo/modsci#SoftComputing': 5, 'https://w3id.org/skgo/modsci#Lasers': 5, 'https://w3id.org/skgo/modsci#BiologicalPhenomena': 3, 'https://w3id.org/skgo/modsci#MetrologicalChemistry': 5, 'https://w3id.org/skgo/modsci#Scientist': 2, 'https://w3id.org/skgo/modsci#AtomicPhysics': 4, 'https://w3id.org/skgo/modsci#FisheriesSciences': 4, 'https://w3id.org/skgo/modsci#Zoology': 4, 'https://w3id.org/skgo/modsci#Technology': 3, 'https://w3id.org/skgo/modsci#ScientificOrganization': 2, 'https://w3id.org/skgo/modsci#HumanSciences': 3, 'https://w3id.org/skgo/modsci#DecisionSupportSystems': 5, 'https://w3id.org/skgo/modsci#AutomatedReasoning': 5, 'https://w3id.org/skgo/modsci#WebSearch': 6, 'https://w3id.org/skgo/modsci#ScienceStudies': 3, 'https://w3id.org/skgo/modsci#MilitaryScience': 3, 'https://w3id.org/skgo/modsci#HealthSciences': 2, 'https://w3id.org/skgo/modsci#GeologicalSciences': 4, 'https://w3id.org/skgo/modsci#StellarAstronomy': 4, 'https://w3id.org/skgo/modsci#Ecology': 4, 'https://w3id.org/skgo/modsci#CommunicationStudies': 3, 'https://w3id.org/skgo/modsci#SocialWork': 3, 'https://w3id.org/skgo/modsci#StructuralChemistry': 5, 'https://w3id.org/skgo/modsci#Radiochemistry': 4, 'https://w3id.org/skgo/modsci#MarineBiology': 4, 'https://w3id.org/skgo/modsci#EvolutionaryComputation': 6, 'https://w3id.org/skgo/modsci#Metrology': 3, 'https://w3id.org/skgo/modsci#Archaeology': 3, 'https://w3id.org/skgo/modsci#Spectroscopy': 5, 'https://w3id.org/skgo/modsci#ComputerVision': 5, 'https://w3id.org/skgo/modsci#Pharmacology': 4, 'https://w3id.org/skgo/modsci#ComputationalPhysics': 4, 'https://w3id.org/skgo/modsci#AcidbaseChemistry': 4, 'https://w3id.org/skgo/modsci#Radiometrics': 5, 'https://w3id.org/skgo/modsci#Algebra': 5, 'https://w3id.org/skgo/modsci#ClassificationAlgorithms': 3, 'https://w3id.org/skgo/modsci#Non-equilibriumProcesses': 5, 'https://w3id.org/skgo/modsci#Biostatistics': 4, 'https://w3id.org/skgo/modsci#Bioethics': 4, 'https://w3id.org/skgo/modsci#NaturalScience': 2, 'https://w3id.org/skgo/modsci#Toxicology': 4, 'https://w3id.org/skgo/modsci#History': 3, 'https://w3id.org/skgo/modsci#SolidStateChemistry': 5, 'https://w3id.org/skgo/modsci#SupramolecularChemistry': 5, 'https://w3id.org/skgo/modsci#FinancialMathematics': 5, 'https://w3id.org/skgo/modsci#MachineLearning': 6, 'https://w3id.org/skgo/modsci#MolecularBiology': 4, 'https://w3id.org/skgo/modsci#Nanochemistry': 5, 'https://w3id.org/skgo/modsci#SurfaceChemistry': 5, 'https://w3id.org/skgo/modsci#InformationSystemsTheory': 5, 'https://w3id.org/skgo/modsci#SocialPsychology': 3, 'https://w3id.org/skgo/modsci#Ethology': 3, 'https://w3id.org/skgo/modsci#Semiotics': 3, 'https://w3id.org/skgo/modsci#Statistics': 3, 'https://w3id.org/skgo/modsci#RelationalDatabases': 6, 'https://w3id.org/skgo/modsci#ArtificialIntelligence': 4, 'https://w3id.org/skgo/modsci#PartialDifferentialEquations': 6, 'https://w3id.org/skgo/modsci#InformationVisualization': 6, 'https://w3id.org/skgo/modsci#VirtualReality': 6, 'https://w3id.org/skgo/modsci#SolidMechanics': 4, 'https://w3id.org/skgo/modsci#MolecularPhysics': 4, 'https://w3id.org/skgo/modsci#ElectroanalyticalChemistry': 5, 'https://w3id.org/skgo/modsci#Computer-HumanInteraction': 5, 'https://w3id.org/skgo/modsci#Optimisation': 5, 'https://w3id.org/skgo/modsci#NaturalPhenomenon': 2, 'https://w3id.org/skgo/modsci#Medicine': 3, 'https://w3id.org/skgo/modsci#QuantumPhysics': 4, 'https://w3id.org/skgo/modsci#OperationsResearch': 5, 'https://w3id.org/skgo/modsci#Forensics': 3, 'https://w3id.org/skgo/modsci#ChemicalThermodynamics': 5, 'https://w3id.org/skgo/modsci#FunctionalAnalysis': 5, 'https://w3id.org/skgo/modsci#Geochemistry': 5, 'https://w3id.org/skgo/modsci#Sociobiology': 4, 'https://w3id.org/skgo/modsci#ComputerSoftware': 4, 'https://w3id.org/skgo/modsci#OrdinaryDifferentialEquations': 6, 'https://w3id.org/skgo/modsci#QuantumMechanics': 4, 'https://w3id.org/skgo/modsci#Photochemistry': 4, 'https://w3id.org/skgo/modsci#Anatomy': 4, 'https://w3id.org/skgo/modsci#Pharmacy': 3, 'https://w3id.org/skgo/modsci#FreeRadicalChemistry': 5, 'https://w3id.org/skgo/modsci#Geodynamics': 5, 'https://w3id.org/skgo/modsci#Sociology': 3, 'https://w3id.org/skgo/modsci#ProgrammingLanguage': 6, 'https://w3id.org/skgo/modsci#DiscoveryOfMethods': 2, 'https://w3id.org/skgo/modsci#Limnology': 4, 'https://w3id.org/skgo/modsci#GeologicalPhenomena': 3, 'https://w3id.org/skgo/modsci#Networking': 6, 'https://w3id.org/skgo/modsci#Neuroscience': 4, 'https://w3id.org/skgo/modsci#WebTechnologies': 6, 'https://w3id.org/skgo/modsci#EvolutionaryPsychology': 3, 'https://w3id.org/skgo/modsci#MaterialsChemistry': 4, 'https://w3id.org/skgo/modsci#ApproximationTheory': 5, 'https://w3id.org/skgo/modsci#Seismology': 5, 'https://w3id.org/skgo/modsci#AutomataTheory': 6, 'https://w3id.org/skgo/modsci#PhysicalChemistry': 4, 'https://w3id.org/skgo/modsci#AnalyticalSpectrometry': 5, 'https://w3id.org/skgo/modsci#OceanographicPhenomena': 3, 'https://w3id.org/skgo/modsci#Phylogeny': 4, 'https://w3id.org/skgo/modsci#ExtraterrestrialGeology': 6, 'https://w3id.org/skgo/modsci#Epidemiology': 3, 'https://w3id.org/skgo/modsci#CalculusOfVariations': 5, 'https://w3id.org/skgo/modsci#Dentistry': 3, 'https://w3id.org/skgo/modsci#AppliedMechanics': 5, 'https://w3id.org/skgo/modsci#Immunology': 4, 'https://w3id.org/skgo/modsci#NeuralEngineering': 3, 'https://w3id.org/skgo/modsci#ImageProcessing': 4, 'https://w3id.org/skgo/modsci#DataFormat': 4, 'https://w3id.org/skgo/modsci#QuantumComputing': 6, 'https://w3id.org/skgo/modsci#Philosophy': 3, 'https://w3id.org/skgo/modsci#Physics': 3, 'https://w3id.org/skgo/modsci#BioinorganicChemistry': 5, 'https://w3id.org/skgo/modsci#CoalGeology': 6, 'https://w3id.org/skgo/modsci#ComputerGraphics': 5, 'https://w3id.org/skgo/modsci#TheoreticalLinguistics': 3, 'https://w3id.org/skgo/modsci#InformationScience': 3, 'https://w3id.org/skgo/modsci#Geodesy': 4, 'https://w3id.org/skgo/modsci#HorticulturalProduction': 4, 'https://w3id.org/skgo/modsci#SportsScience': 3, 'https://w3id.org/skgo/modsci#Geophysics': 4, 'https://w3id.org/skgo/modsci#AnimalProduction': 4, 'https://w3id.org/skgo/modsci#CognitiveScience': 3, 'https://w3id.org/skgo/modsci#ComputabilityTheory': 6, 'https://w3id.org/skgo/modsci#SolutionChemistry': 5, 'https://w3id.org/skgo/modsci#MathematicalPhysics': 3, 'https://w3id.org/skgo/modsci#VeterinarySciences': 4, 'https://w3id.org/skgo/modsci#UbiquitousComputing': 6, 'https://w3id.org/skgo/modsci#Colloid': 5, 'https://w3id.org/skgo/modsci#Biotechnology': 4, 'https://w3id.org/skgo/modsci#AstronomicalPhenomena': 3, 'https://w3id.org/skgo/modsci#EthnicStudies': 3, 'https://w3id.org/skgo/modsci#ChemicalCharacterisationOfMaterials': 5, 'https://w3id.org/skgo/modsci#GalacticAstronomy': 4, 'https://w3id.org/skgo/modsci#Bioengineering': 4, 'https://w3id.org/skgo/modsci#Gerontology': 4, 'https://w3id.org/skgo/modsci#ComputerApplications': 4, 'https://w3id.org/skgo/modsci#Biochemistry': 4, 'https://w3id.org/skgo/modsci#InformationSystemsManagement': 5, 'https://w3id.org/skgo/modsci#FormalScience': 2, 'https://w3id.org/skgo/modsci#SystemsScience': 3, 'https://w3id.org/skgo/modsci#ConceptualModelling': 5, 'https://w3id.org/skgo/modsci#FoodChemistry': 4, 'https://w3id.org/skgo/modsci#Nursing': 3, 'https://w3id.org/skgo/modsci#Waves': 5, 'https://w3id.org/skgo/modsci#CodingAndInformationTheory': 5, 'https://w3id.org/skgo/modsci#MarkupLanguages': 5, 'https://w3id.org/skgo/modsci#CropProduction': 4, 'https://w3id.org/skgo/modsci#ChemicalOceanography': 5, 'https://w3id.org/skgo/modsci#BasinAnalysis': 6, 'https://w3id.org/skgo/modsci#MobileTechnologies': 6, 'https://w3id.org/skgo/modsci#Mathematics': 3, 'https://w3id.org/skgo/modsci#Thermodynamics': 5, 'https://w3id.org/skgo/modsci#Photonics': 5, 'https://w3id.org/skgo/modsci#Geochronology': 6, 'https://w3id.org/skgo/modsci#Astrobiology': 4, 'https://w3id.org/skgo/modsci#ScienceAndTechnologyStudies': 3, 'https://w3id.org/skgo/modsci#Oceanography': 4, 'https://w3id.org/skgo/modsci#ComputerSystemArchitecture': 5, 'https://w3id.org/skgo/modsci#OperatingSystems': 5, 'https://w3id.org/skgo/modsci#Catalysis': 5, 'https://w3id.org/skgo/modsci#Economics': 3, 'https://w3id.org/skgo/modsci#PhysicalPhenomena': 3, 'https://w3id.org/skgo/modsci#PlanetaryScience': 4, 'https://w3id.org/skgo/modsci#SoilBiology': 4, 'https://w3id.org/skgo/modsci#MetamorphicPetrology': 6, 'https://w3id.org/skgo/modsci#ParallelComputing': 6, 'https://w3id.org/skgo/modsci#Optics': 3, 'https://w3id.org/skgo/modsci#SoilScience': 4, 'https://w3id.org/skgo/modsci#Electrostatics': 5, 'https://w3id.org/skgo/modsci#AppliedSciences': 2, 'https://w3id.org/skgo/modsci#ScientificModeling': 3, 'https://w3id.org/skgo/modsci#MathematicalAndTheoreticalBiology': 4, 'https://w3id.org/skgo/modsci#Magnetism': 5, 'https://w3id.org/skgo/modsci#PlasmaPhysics': 4, 'https://w3id.org/skgo/modsci#Astronomy': 3, 'https://w3id.org/skgo/modsci#NuclearPhysics': 4, 'https://w3id.org/skgo/modsci#MechanismsOfReactions': 5, 'https://w3id.org/skgo/modsci#Metallurgy': 4, 'https://w3id.org/skgo/modsci#OrganometallicChemistry': 4, 'https://w3id.org/skgo/modsci#OpticalPhysics': 4, 'https://w3id.org/skgo/modsci#EnvironmentalScience': 4, 'https://w3id.org/skgo/modsci#Electrodynamics': 5, 'https://w3id.org/skgo/modsci#InterdisciplinaryStudies': 2, 'https://w3id.org/skgo/modsci#Informetrics': 5, 'https://w3id.org/skgo/modsci#UniversalAlgebra': 6, 'https://w3id.org/skgo/modsci#SynthesisOfMaterials': 5, 'https://w3id.org/skgo/modsci#OrganicChemicalSynthesis': 5, 'https://w3id.org/skgo/modsci#OrganicChemistry': 4, 'https://w3id.org/skgo/modsci#ComputerSecurity': 6, 'https://w3id.org/skgo/modsci#LibraryScience': 3, 'https://w3id.org/skgo/modsci#Measurement': 3, 'https://w3id.org/skgo/modsci#CulturalStudies': 3, 'https://w3id.org/skgo/modsci#FluidPhysics': 5, 'https://w3id.org/skgo/modsci#TheoreticalBiology': 4, 'https://w3id.org/skgo/modsci#Engineering': 3, 'https://w3id.org/skgo/modsci#PolymerisationMechanisms': 5, 'https://w3id.org/skgo/modsci#GlobalInformationSystems': 5, 'https://w3id.org/skgo/modsci#Museology': 3, 'https://w3id.org/skgo/modsci#Robotics': 5, 'https://w3id.org/skgo/modsci#PatternRecognition': 5, 'https://w3id.org/skgo/modsci#PureMathematics': 4, 'https://w3id.org/skgo/modsci#ColloidalChemistry': 4, 'https://w3id.org/skgo/modsci#ReverseEngineering': 6, 'https://w3id.org/skgo/modsci#ComputerConcurrency': 6, 'https://w3id.org/skgo/modsci#Cybernetics': 3, 'https://w3id.org/skgo/modsci#Mineralogy': 6, 'https://w3id.org/skgo/modsci#Astrochemistry': 4, 'https://w3id.org/skgo/modsci#Algorithms': 2, 'https://w3id.org/skgo/modsci#ExperimentalPhysics': 4, 'https://w3id.org/skgo/modsci#ProgrammingLanguages': 5, 'https://w3id.org/skgo/modsci#Topology': 5, 'https://w3id.org/skgo/modsci#ForestrySciences': 4, 'https://w3id.org/skgo/modsci#Architecture': 3, 'https://w3id.org/skgo/modsci#Transdisciplinarity': 3, 'https://w3id.org/skgo/modsci#Non-metalChemistry': 5, 'https://w3id.org/skgo/modsci#Psychology': 3, 'https://w3id.org/skgo/modsci#CondensedMatterPhysics': 4, 'https://w3id.org/skgo/modsci#Volcanology': 6, 'https://w3id.org/skgo/modsci#Biophysics': 4, 'https://w3id.org/skgo/modsci#Hydrology': 4, 'https://w3id.org/skgo/modsci#Palaeontology': 6, 'https://w3id.org/skgo/modsci#NaturalProductsChemistry': 5, 'https://w3id.org/skgo/modsci#ScientificInstrument': 2, 'https://w3id.org/skgo/modsci#PoliticalScience': 3, 'https://w3id.org/skgo/modsci#GreenChemistry': 4, 'https://w3id.org/skgo/modsci#UrbanPlanning': 3, 'https://w3id.org/skgo/modsci#LaboratoryInstrument': 2, 'https://w3id.org/skgo/modsci#Palaeomagnetism': 5, 'https://w3id.org/skgo/modsci#ParticlePhysics': 4, 'https://w3id.org/skgo/modsci#QuantumOptics': 5, 'https://w3id.org/skgo/modsci#InformationRetrieval': 5, 'https://w3id.org/skgo/modsci#MedicinalChemistry': 4, 'https://w3id.org/skgo/modsci#DistributedComputing': 6, 'https://w3id.org/skgo/modsci#HumanComputerInteraction': 6, 'https://w3id.org/skgo/modsci#Paleontology': 4, 'https://w3id.org/skgo/modsci#InorganicGreenChemistry': 5, 'https://w3id.org/skgo/modsci#SoftwareEngineering': 5, 'https://w3id.org/skgo/modsci#ComputationalLinguistics': 3, 'https://w3id.org/skgo/modsci#Biology': 3, 'https://w3id.org/skgo/modsci#OpticalCommunications': 5, 'https://w3id.org/skgo/modsci#VeterinaryMedicine': 3, 'https://w3id.org/skgo/modsci#Metabolism': 4, 'https://w3id.org/skgo/modsci#SeparationScience': 5, 'https://w3id.org/skgo/modsci#MainGroupMetalChemistry': 5, 'https://w3id.org/skgo/modsci#Optoelectronics': 5, 'https://w3id.org/skgo/modsci#Ethnobiology': 4, 'https://w3id.org/skgo/modsci#PhysicalOceanography': 5, 'https://w3id.org/skgo/modsci#StructuralGeology': 6, 'https://w3id.org/skgo/modsci#HomologicalAlgebra': 6, 'https://w3id.org/skgo/modsci#EcologicalApplications': 5, 'https://w3id.org/skgo/modsci#Geomorphology': 4, 'https://w3id.org/skgo/modsci#Biopsychology': 4, 'https://w3id.org/skgo/modsci#KnowledgeSystems': 5, 'https://w3id.org/skgo/modsci#Geology': 5, 'https://w3id.org/skgo/modsci#Geothermics': 5, 'https://w3id.org/skgo/modsci#Geography': 4, 'https://w3id.org/skgo/modsci#MathematicalLogic': 5, 'https://w3id.org/skgo/modsci#Crystallography': 4, 'https://w3id.org/skgo/modsci#InformationSystems': 4, 'https://w3id.org/skgo/modsci#NumericalAnalysis': 5, 'https://w3id.org/skgo/modsci#DatabaseManagement': 5, 'https://w3id.org/skgo/modsci#Agronomy': 4, 'https://w3id.org/skgo/modsci#Agriculture': 3, 'https://w3id.org/skgo/modsci#SpaceScience': 4, 'https://w3id.org/skgo/modsci#PhysicalGeography': 4, 'https://w3id.org/skgo/modsci#Palynology': 4, 'https://w3id.org/skgo/modsci#Radiobiology': 4, 'https://w3id.org/skgo/modsci#ChemicalPhenomena': 3, 'https://w3id.org/skgo/modsci#Electrochemistry': 5, 'https://w3id.org/skgo/modsci#DiscoveryOfPhenomenon': 2, 'https://w3id.org/skgo/modsci#FlowAnalysis': 5, 'https://w3id.org/skgo/modsci#Gravimetrics': 5, 'https://w3id.org/skgo/modsci#EarthScience': 3, 'https://w3id.org/skgo/modsci#PhysicalOrganicChemistry': 5, 'https://w3id.org/skgo/modsci#ComputationalMathematics': 4, 'https://w3id.org/skgo/modsci#SocialSciences': 2, 'https://w3id.org/skgo/modsci#ChemicalEngineering': 4, 'https://w3id.org/skgo/modsci#AppliedMathematics': 4, 'https://w3id.org/skgo/modsci#DataStructures': 5, 'https://w3id.org/skgo/modsci#DistributedSystems': 5, 'https://w3id.org/skgo/modsci#ComputationalComplexityTheory': 6, 'https://w3id.org/skgo/modsci#Mechanics': 4, 'https://w3id.org/skgo/modsci#PoliticalEconomy': 3, 'https://w3id.org/skgo/modsci#NuclearChemistry': 4, 'https://w3id.org/skgo/modsci#Bioinformatics': 4, 'https://w3id.org/skgo/modsci#CompilerTheory': 6, 'https://w3id.org/skgo/modsci#GeophysicalFluidDynamics': 5, 'https://w3id.org/skgo/modsci#InorganicChemistry': 4, 'https://w3id.org/skgo/modsci#Astrometry': 4, 'https://w3id.org/skgo/modsci#AtmosphericSciences': 4, 'https://w3id.org/skgo/modsci#IndustrialScience': 3, 'https://w3id.org/skgo/modsci#Ergonomics': 3, 'https://w3id.org/skgo/modsci#CommunicationAndSecurity': 5, 'https://w3id.org/skgo/modsci#Acoustics': 5, 'https://w3id.org/skgo/modsci#Cosmology': 4, 'https://w3id.org/skgo/modsci#Genetics': 4, 'https://w3id.org/skgo/modsci#ComputerScience': 3, 'https://w3id.org/skgo/modsci#SeismicExploration': 5, 'https://w3id.org/skgo/modsci#DataEncryption': 5, 'https://w3id.org/skgo/modsci#Semantics': 6, 'https://w3id.org/skgo/modsci#Parasitology': 4}

In [20]:
list_of_depths = pd.DataFrame.from_dict(concepts, orient='index', columns=['depth'])

In [21]:
list_of_depths.sort_values('depth', inplace=True, ascending=False)
list_of_depths.head()

                                                   depth
https://w3id.org/skgo/modsci#CompilerTheory            6
https://w3id.org/skgo/modsci#MetamorphicPetrology      6
https://w3id.org/skgo/modsci#CoalGeology               6
https://w3id.org/skgo/modsci#ProgrammingLanguage       6
https://w3id.org/skgo/modsci#StructuredStorage         6

In [22]:
print(json.dumps(unhier,indent=4))

{
    "https://w3id.org/skgo/modsci#Education": [
        "https://w3id.org/skgo/modsci#AppliedSciences"
    ],
    "https://w3id.org/skgo/modsci#Cryobiology": [
        "https://w3id.org/skgo/modsci#Biology"
    ],
    "https://w3id.org/skgo/modsci#ProgrammingLanguageTheory": [
        "https://w3id.org/skgo/modsci#ProgrammingLanguages"
    ],
    "https://w3id.org/skgo/modsci#OrganicGreenChemistry": [
        "https://w3id.org/skgo/modsci#OrganicChemistry"
    ],
    "https://w3id.org/skgo/modsci#IntegralEquations": [
        "https://w3id.org/skgo/modsci#ComputationalMathematics"
    ],
    "https://w3id.org/skgo/modsci#SoilSciences": [
        "https://w3id.org/skgo/modsci#EnvironmentalScience"
    ],
    "https://w3id.org/skgo/modsci#Forestry": [
        "https://w3id.org/skgo/modsci#Biology"
    ],
    "https://w3id.org/skgo/modsci#Ethnology": [
        "https://w3id.org/skgo/modsci#SocialSciences"
    ],
    "https://w3id.org/skgo/modsci#ClassicalPhysics": [
        "https://w3id.org/skgo/modsci#Physics"
    ],
    "https://w3id.org/skgo/modsci#TheoreticalChemistry": [
        "https://w3id.org/skgo/modsci#Chemistry"
    ],
    "https://w3id.org/skgo/modsci#TheoryOfComputation": [
        "https://w3id.org/skgo/modsci#TheoreticalComputerScience"
    ],
    "https://w3id.org/skgo/modsci#TheoreticalComputerScience": [
        "https://w3id.org/skgo/modsci#ComputerScience"
    ],
    "https://w3id.org/skgo/modsci#EnvironmentalChemistry": [
        "https://w3id.org/skgo/modsci#Chemistry"
    ],
    "https://w3id.org/skgo/modsci#MultimediaProgramming": [
        "https://w3id.org/skgo/modsci#ComputerSoftware"
    ],
    "https://w3id.org/skgo/modsci#Anthropology": [
        "https://w3id.org/skgo/modsci#SocialSciences"
    ],
    "https://w3id.org/skgo/modsci#TypeTheory": [
        "https://w3id.org/skgo/modsci#ProgrammingLanguages"
    ],
    "https://w3id.org/skgo/modsci#EvolutionaryBiology": [
        "https://w3id.org/skgo/modsci#Biology"
    ],
    "https://w3id.org/skgo/modsci#TheoryAndDesignOfMaterials": [
        "https://w3id.org/skgo/modsci#MaterialsChemistry"
    ],
    "https://w3id.org/skgo/modsci#InterorganisationalInformationSystems": [
        "https://w3id.org/skgo/modsci#InformationSystems"
    ],
    "https://w3id.org/skgo/modsci#BioinformaticsSoftware": [
        "https://w3id.org/skgo/modsci#ComputerSoftware"
    ],
    "https://w3id.org/skgo/modsci#AnalyticalChemistry": [
        "https://w3id.org/skgo/modsci#Chemistry"
    ],
    "https://w3id.org/skgo/modsci#TransitionMetalChemistry": [
        "https://w3id.org/skgo/modsci#InorganicChemistry"
    ],
    "https://w3id.org/skgo/modsci#MeteorologicalPhenomena": [
        "https://w3id.org/skgo/modsci#NaturalPhenomenon"
    ],
    "https://w3id.org/skgo/modsci#BiomedicalEngineering": [
        "https://w3id.org/skgo/modsci#InterdisciplinaryStudies"
    ],
    "https://w3id.org/skgo/modsci#BehaviouralSciences": [
        "https://w3id.org/skgo/modsci#ModernScience"
    ],
    "https://w3id.org/skgo/modsci#NumberTheory": [
        "https://w3id.org/skgo/modsci#PureMathematics"
    ],
    "https://w3id.org/skgo/modsci#Biogeography": [
        "https://w3id.org/skgo/modsci#Biology"
    ],
    "https://w3id.org/skgo/modsci#BiologicalOceanography": [
        "https://w3id.org/skgo/modsci#Oceanography"
    ],
    "https://w3id.org/skgo/modsci#Healthcare": [
        "https://w3id.org/skgo/modsci#HealthSciences"
    ],
    "https://w3id.org/skgo/modsci#StructuredStorage": [
        "https://w3id.org/skgo/modsci#DatabaseManagement"
    ],
    "https://w3id.org/skgo/modsci#AtmosphericPhenomena": [
        "https://w3id.org/skgo/modsci#NaturalPhenomenon"
    ],
    "https://w3id.org/skgo/modsci#DevelopmentalBiology": [
        "https://w3id.org/skgo/modsci#Biology"
    ],
    "https://w3id.org/skgo/modsci#DataMining": [
        "https://w3id.org/skgo/modsci#DatabaseManagement"
    ],
    "https://w3id.org/skgo/modsci#NonlinearOptics": [
        "https://w3id.org/skgo/modsci#OpticalPhysics"
    ],
    "https://w3id.org/skgo/modsci#f-BlockChemistry": [
        "https://w3id.org/skgo/modsci#InorganicChemistry"
    ],
    "https://w3id.org/skgo/modsci#Paleoclimatology": [
        "https://w3id.org/skgo/modsci#EarthScience"
    ],
    "https://w3id.org/skgo/modsci#OreDepositPetrology": [
        "https://w3id.org/skgo/modsci#Geology"
    ],
    "https://w3id.org/skgo/modsci#Chemistry": [
        "https://w3id.org/skgo/modsci#NaturalScience"
    ],
    "https://w3id.org/skgo/modsci#DifferentialEquations": [
        "https://w3id.org/skgo/modsci#PureMathematics"
    ],
    "https://w3id.org/skgo/modsci#CellBiology": [
        "https://w3id.org/skgo/modsci#Biology"
    ],
    "https://w3id.org/skgo/modsci#ExtragalacticAstronomy": [
        "https://w3id.org/skgo/modsci#Astronomy"
    ],
    "https://w3id.org/skgo/modsci#WebServices": [
        "https://w3id.org/skgo/modsci#InformationSystems"
    ],
    "https://w3id.org/skgo/modsci#PastureProduction": [
        "https://w3id.org/skgo/modsci#Agriculture"
    ],
    "https://w3id.org/skgo/modsci#SocialPhenomenon": [
        "http://sweetontology.net/phen/Phenomenon"
    ],
    "https://w3id.org/skgo/modsci#AppliedPhysics": [
        "https://w3id.org/skgo/modsci#InterdisciplinaryStudies",
        "https://w3id.org/skgo/modsci#Physics"
    ],
    "https://w3id.org/skgo/modsci#Logic": [
        "https://w3id.org/skgo/modsci#InterdisciplinaryStudies"
    ],
    "https://w3id.org/skgo/modsci#Botany": [
        "https://w3id.org/skgo/modsci#Biology"
    ],
    "https://w3id.org/skgo/modsci#Cryptography": [
        "https://w3id.org/skgo/modsci#CommunicationAndSecurity"
    ],
    "https://w3id.org/skgo/modsci#Linguistics": [
        "https://w3id.org/skgo/modsci#SocialSciences"
    ],
    "https://w3id.org/skgo/modsci#Stratigraphy": [
        "https://w3id.org/skgo/modsci#Geology"
    ],
    "https://w3id.org/skgo/modsci#Tectonics": [
        "https://w3id.org/skgo/modsci#Geology"
    ],
    "https://w3id.org/skgo/modsci#Health": [
        "https://w3id.org/skgo/modsci#InterdisciplinaryStudies"
    ],
    "https://w3id.org/skgo/modsci#PetroleumGeology": [
        "https://w3id.org/skgo/modsci#Geology"
    ],
    "https://w3id.org/skgo/modsci#Glaciology": [
        "https://w3id.org/skgo/modsci#EarthScience"
    ],
    "https://w3id.org/skgo/modsci#Sedimentology": [
        "https://w3id.org/skgo/modsci#Geology"
    ],
    "https://w3id.org/skgo/modsci#Stereochemistry": [
        "https://w3id.org/skgo/modsci#Chemistry"
    ],
    "https://w3id.org/skgo/modsci#NaturalLanguageProcessing": [
        "https://w3id.org/skgo/modsci#ArtificialIntelligence",
        "https://w3id.org/skgo/modsci#ComputerSoftware",
        "https://w3id.org/skgo/modsci#Linguistics"
    ],
    "https://w3id.org/skgo/modsci#DiscreteMathematics": [
        "https://w3id.org/skgo/modsci#PureMathematics"
    ],
    "https://w3id.org/skgo/modsci#Physiology": [
        "https://w3id.org/skgo/modsci#Biology"
    ],
    "https://w3id.org/skgo/modsci#BiologicalMathematics": [
        "https://w3id.org/skgo/modsci#AppliedMathematics"
    ],
    "https://w3id.org/skgo/modsci#SoftComputing": [
        "https://w3id.org/skgo/modsci#ArtificialIntelligence"
    ],
    "https://w3id.org/skgo/modsci#Lasers": [
        "https://w3id.org/skgo/modsci#OpticalPhysics"
    ],
    "https://w3id.org/skgo/modsci#BiologicalPhenomena": [
        "https://w3id.org/skgo/modsci#NaturalPhenomenon"
    ],
    "https://w3id.org/skgo/modsci#MetrologicalChemistry": [
        "https://w3id.org/skgo/modsci#AnalyticalChemistry"
    ],
    "https://w3id.org/skgo/modsci#Scientist": [
        "http://xmlns.com/foaf/0.1/Person"
    ],
    "https://w3id.org/skgo/modsci#AtomicPhysics": [
        "https://w3id.org/skgo/modsci#Physics"
    ],
    "https://w3id.org/skgo/modsci#FisheriesSciences": [
        "https://w3id.org/skgo/modsci#Agriculture"
    ],
    "https://w3id.org/skgo/modsci#Zoology": [
        "https://w3id.org/skgo/modsci#Biology"
    ],
    "https://w3id.org/skgo/modsci#Technology": [
        "https://w3id.org/skgo/modsci#FormalScience"
    ],
    "https://w3id.org/skgo/modsci#ScientificOrganization": [
        "http://xmlns.com/foaf/0.1/Organization"
    ],
    "https://w3id.org/skgo/modsci#HumanSciences": [
        "https://w3id.org/skgo/modsci#InterdisciplinaryStudies"
    ],
    "https://w3id.org/skgo/modsci#DecisionSupportSystems": [
        "https://w3id.org/skgo/modsci#InformationSystems"
    ],
    "https://w3id.org/skgo/modsci#AutomatedReasoning": [
        "https://w3id.org/skgo/modsci#ArtificialIntelligence"
    ],
    "https://w3id.org/skgo/modsci#WebSearch": [
        "https://w3id.org/skgo/modsci#InformationRetrieval"
    ],
    "https://w3id.org/skgo/modsci#ScienceStudies": [
        "https://w3id.org/skgo/modsci#InterdisciplinaryStudies"
    ],
    "https://w3id.org/skgo/modsci#MilitaryScience": [
        "https://w3id.org/skgo/modsci#AppliedSciences"
    ],
    "https://w3id.org/skgo/modsci#HealthSciences": [
        "https://w3id.org/skgo/modsci#ModernScience"
    ],
    "https://w3id.org/skgo/modsci#GeologicalSciences": [
        "https://w3id.org/skgo/modsci#EarthScience"
    ],
    "https://w3id.org/skgo/modsci#StellarAstronomy": [
        "https://w3id.org/skgo/modsci#Astronomy"
    ],
    "https://w3id.org/skgo/modsci#Ecology": [
        "https://w3id.org/skgo/modsci#Biology",
        "https://w3id.org/skgo/modsci#EarthScience"
    ],
    "https://w3id.org/skgo/modsci#CommunicationStudies": [
        "https://w3id.org/skgo/modsci#SocialSciences"
    ],
    "https://w3id.org/skgo/modsci#SocialWork": [
        "https://w3id.org/skgo/modsci#HealthSciences"
    ],
    "https://w3id.org/skgo/modsci#StructuralChemistry": [
        "https://w3id.org/skgo/modsci#PhysicalChemistry"
    ],
    "https://w3id.org/skgo/modsci#Radiochemistry": [
        "https://w3id.org/skgo/modsci#Chemistry"
    ],
    "https://w3id.org/skgo/modsci#MarineBiology": [
        "https://w3id.org/skgo/modsci#Biology"
    ],
    "https://w3id.org/skgo/modsci#EvolutionaryComputation": [
        "https://w3id.org/skgo/modsci#SoftComputing"
    ],
    "https://w3id.org/skgo/modsci#Metrology": [
        "https://w3id.org/skgo/modsci#AppliedSciences"
    ],
    "https://w3id.org/skgo/modsci#Archaeology": [
        "https://w3id.org/skgo/modsci#SocialSciences"
    ],
    "https://w3id.org/skgo/modsci#Spectroscopy": [
        "https://w3id.org/skgo/modsci#OpticalPhysics"
    ],
    "https://w3id.org/skgo/modsci#ComputerVision": [
        "https://w3id.org/skgo/modsci#ArtificialIntelligence"
    ],
    "https://w3id.org/skgo/modsci#Pharmacology": [
        "https://w3id.org/skgo/modsci#Biology"
    ],
    "https://w3id.org/skgo/modsci#ComputationalPhysics": [
        "https://w3id.org/skgo/modsci#Physics"
    ],
    "https://w3id.org/skgo/modsci#AcidbaseChemistry": [
        "https://w3id.org/skgo/modsci#Chemistry"
    ],
    "https://w3id.org/skgo/modsci#Radiometrics": [
        "https://w3id.org/skgo/modsci#Geophysics"
    ],
    "https://w3id.org/skgo/modsci#Algebra": [
        "https://w3id.org/skgo/modsci#PureMathematics"
    ],
    "https://w3id.org/skgo/modsci#ClassificationAlgorithms": [
        "https://w3id.org/skgo/modsci#Algorithms"
    ],
    "https://w3id.org/skgo/modsci#Non-equilibriumProcesses": [
        "https://w3id.org/skgo/modsci#PhysicalChemistry"
    ],
    "https://w3id.org/skgo/modsci#Biostatistics": [
        "https://w3id.org/skgo/modsci#Biology"
    ],
    "https://w3id.org/skgo/modsci#Bioethics": [
        "https://w3id.org/skgo/modsci#Biology"
    ],
    "https://w3id.org/skgo/modsci#NaturalScience": [
        "https://w3id.org/skgo/modsci#ModernScience"
    ],
    "https://w3id.org/skgo/modsci#Toxicology": [
        "https://w3id.org/skgo/modsci#Biology"
    ],
    "https://w3id.org/skgo/modsci#History": [
        "https://w3id.org/skgo/modsci#FormalScience"
    ],
    "https://w3id.org/skgo/modsci#SolidStateChemistry": [
        "https://w3id.org/skgo/modsci#InorganicChemistry"
    ],
    "https://w3id.org/skgo/modsci#SupramolecularChemistry": [
        "https://w3id.org/skgo/modsci#MaterialsChemistry"
    ],
    "https://w3id.org/skgo/modsci#FinancialMathematics": [
        "https://w3id.org/skgo/modsci#AppliedMathematics"
    ],
    "https://w3id.org/skgo/modsci#MachineLearning": [
        "https://w3id.org/skgo/modsci#SoftComputing"
    ],
    "https://w3id.org/skgo/modsci#MolecularBiology": [
        "https://w3id.org/skgo/modsci#Biology"
    ],
    "https://w3id.org/skgo/modsci#Nanochemistry": [
        "https://w3id.org/skgo/modsci#MaterialsChemistry"
    ],
    "https://w3id.org/skgo/modsci#SurfaceChemistry": [
        "https://w3id.org/skgo/modsci#PhysicalChemistry"
    ],
    "https://w3id.org/skgo/modsci#InformationSystemsTheory": [
        "https://w3id.org/skgo/modsci#InformationSystems"
    ],
    "https://w3id.org/skgo/modsci#SocialPsychology": [
        "https://w3id.org/skgo/modsci#BehaviouralSciences"
    ],
    "https://w3id.org/skgo/modsci#Ethology": [
        "https://w3id.org/skgo/modsci#BehaviouralSciences"
    ],
    "https://w3id.org/skgo/modsci#Semiotics": [
        "https://w3id.org/skgo/modsci#InterdisciplinaryStudies",
        "https://w3id.org/skgo/modsci#SocialSciences"
    ],
    "https://w3id.org/skgo/modsci#Statistics": [
        "https://w3id.org/skgo/modsci#FormalScience"
    ],
    "https://w3id.org/skgo/modsci#RelationalDatabases": [
        "https://w3id.org/skgo/modsci#DatabaseManagement"
    ],
    "https://w3id.org/skgo/modsci#ArtificialIntelligence": [
        "https://w3id.org/skgo/modsci#ComputerScience"
    ],
    "https://w3id.org/skgo/modsci#PartialDifferentialEquations": [
        "https://w3id.org/skgo/modsci#DifferentialEquations"
    ],
    "https://w3id.org/skgo/modsci#InformationVisualization": [
        "https://w3id.org/skgo/modsci#ComputerGraphics"
    ],
    "https://w3id.org/skgo/modsci#VirtualReality": [
        "https://w3id.org/skgo/modsci#ComputerGraphics"
    ],
    "https://w3id.org/skgo/modsci#SolidMechanics": [
        "https://w3id.org/skgo/modsci#Physics"
    ],
    "https://w3id.org/skgo/modsci#MolecularPhysics": [
        "https://w3id.org/skgo/modsci#Physics"
    ],
    "https://w3id.org/skgo/modsci#ElectroanalyticalChemistry": [
        "https://w3id.org/skgo/modsci#AnalyticalChemistry"
    ],
    "https://w3id.org/skgo/modsci#Computer-HumanInteraction": [
        "https://w3id.org/skgo/modsci#InformationSystems"
    ],
    "https://w3id.org/skgo/modsci#Optimisation": [
        "https://w3id.org/skgo/modsci#ComputationalMathematics"
    ],
    "https://w3id.org/skgo/modsci#NaturalPhenomenon": [
        "http://sweetontology.net/phen/Phenomenon"
    ],
    "https://w3id.org/skgo/modsci#Medicine": [
        "https://w3id.org/skgo/modsci#HealthSciences"
    ],
    "https://w3id.org/skgo/modsci#QuantumPhysics": [
        "https://w3id.org/skgo/modsci#Physics"
    ],
    "https://w3id.org/skgo/modsci#OperationsResearch": [
        "https://w3id.org/skgo/modsci#AppliedMathematics"
    ],
    "https://w3id.org/skgo/modsci#Forensics": [
        "https://w3id.org/skgo/modsci#AppliedSciences"
    ],
    "https://w3id.org/skgo/modsci#ChemicalThermodynamics": [
        "https://w3id.org/skgo/modsci#PhysicalChemistry"
    ],
    "https://w3id.org/skgo/modsci#FunctionalAnalysis": [
        "https://w3id.org/skgo/modsci#PureMathematics"
    ],
    "https://w3id.org/skgo/modsci#Geochemistry": [
        "https://w3id.org/skgo/modsci#Chemistry",
        "https://w3id.org/skgo/modsci#Geology"
    ],
    "https://w3id.org/skgo/modsci#Sociobiology": [
        "https://w3id.org/skgo/modsci#BehaviouralSciences",
        "https://w3id.org/skgo/modsci#Biology"
    ],
    "https://w3id.org/skgo/modsci#ComputerSoftware": [
        "https://w3id.org/skgo/modsci#ComputerScience"
    ],
    "https://w3id.org/skgo/modsci#OrdinaryDifferentialEquations": [
        "https://w3id.org/skgo/modsci#DifferentialEquations"
    ],
    "https://w3id.org/skgo/modsci#QuantumMechanics": [
        "https://w3id.org/skgo/modsci#Physics"
    ],
    "https://w3id.org/skgo/modsci#Photochemistry": [
        "https://w3id.org/skgo/modsci#Chemistry"
    ],
    "https://w3id.org/skgo/modsci#Anatomy": [
        "https://w3id.org/skgo/modsci#Biology"
    ],
    "https://w3id.org/skgo/modsci#Pharmacy": [
        "https://w3id.org/skgo/modsci#HealthSciences"
    ],
    "https://w3id.org/skgo/modsci#FreeRadicalChemistry": [
        "https://w3id.org/skgo/modsci#OrganicChemistry"
    ],
    "https://w3id.org/skgo/modsci#Geodynamics": [
        "https://w3id.org/skgo/modsci#Geophysics"
    ],
    "https://w3id.org/skgo/modsci#Sociology": [
        "https://w3id.org/skgo/modsci#SocialSciences"
    ],
    "https://w3id.org/skgo/modsci#ProgrammingLanguage": [
        "https://w3id.org/skgo/modsci#ProgrammingLanguages"
    ],
    "https://w3id.org/skgo/modsci#DiscoveryOfMethods": [
        "https://w3id.org/skgo/modsci#ScientificDiscovery"
    ],
    "https://w3id.org/skgo/modsci#Limnology": [
        "https://w3id.org/skgo/modsci#Biology",
        "https://w3id.org/skgo/modsci#EarthScience"
    ],
    "https://w3id.org/skgo/modsci#GeologicalPhenomena": [
        "https://w3id.org/skgo/modsci#NaturalPhenomenon"
    ],
    "https://w3id.org/skgo/modsci#Networking": [
        "https://w3id.org/skgo/modsci#CommunicationAndSecurity"
    ],
    "https://w3id.org/skgo/modsci#Neuroscience": [
        "https://w3id.org/skgo/modsci#Biology",
        "https://w3id.org/skgo/modsci#InterdisciplinaryStudies"
    ],
    "https://w3id.org/skgo/modsci#WebTechnologies": [
        "https://w3id.org/skgo/modsci#DistributedSystems"
    ],
    "https://w3id.org/skgo/modsci#EvolutionaryPsychology": [
        "https://w3id.org/skgo/modsci#InterdisciplinaryStudies"
    ],
    "https://w3id.org/skgo/modsci#MaterialsChemistry": [
        "https://w3id.org/skgo/modsci#Chemistry"
    ],
    "https://w3id.org/skgo/modsci#ApproximationTheory": [
        "https://w3id.org/skgo/modsci#AppliedMathematics"
    ],
    "https://w3id.org/skgo/modsci#Seismology": [
        "https://w3id.org/skgo/modsci#Geophysics"
    ],
    "https://w3id.org/skgo/modsci#AutomataTheory": [
        "https://w3id.org/skgo/modsci#TheoryOfComputation"
    ],
    "https://w3id.org/skgo/modsci#PhysicalChemistry": [
        "https://w3id.org/skgo/modsci#Chemistry"
    ],
    "https://w3id.org/skgo/modsci#AnalyticalSpectrometry": [
        "https://w3id.org/skgo/modsci#AnalyticalChemistry"
    ],
    "https://w3id.org/skgo/modsci#OceanographicPhenomena": [
        "https://w3id.org/skgo/modsci#NaturalPhenomenon"
    ],
    "https://w3id.org/skgo/modsci#Phylogeny": [
        "https://w3id.org/skgo/modsci#Biology"
    ],
    "https://w3id.org/skgo/modsci#ExtraterrestrialGeology": [
        "https://w3id.org/skgo/modsci#Geology"
    ],
    "https://w3id.org/skgo/modsci#Epidemiology": [
        "https://w3id.org/skgo/modsci#HealthSciences"
    ],
    "https://w3id.org/skgo/modsci#CalculusOfVariations": [
        "https://w3id.org/skgo/modsci#AppliedMathematics"
    ],
    "https://w3id.org/skgo/modsci#Dentistry": [
        "https://w3id.org/skgo/modsci#HealthSciences"
    ],
    "https://w3id.org/skgo/modsci#AppliedMechanics": [
        "https://w3id.org/skgo/modsci#AppliedMathematics"
    ],
    "https://w3id.org/skgo/modsci#Immunology": [
        "https://w3id.org/skgo/modsci#Biology"
    ],
    "https://w3id.org/skgo/modsci#NeuralEngineering": [
        "https://w3id.org/skgo/modsci#InterdisciplinaryStudies"
    ],
    "https://w3id.org/skgo/modsci#ImageProcessing": [
        "https://w3id.org/skgo/modsci#ComputerScience"
    ],
    "https://w3id.org/skgo/modsci#DataFormat": [
        "https://w3id.org/skgo/modsci#ComputerScience"
    ],
    "https://w3id.org/skgo/modsci#QuantumComputing": [
        "https://w3id.org/skgo/modsci#TheoryOfComputation"
    ],
    "https://w3id.org/skgo/modsci#Philosophy": [